[supervisord]
nodaemon=true

[program:retover-api]
directory=%(here)s
command=uvicorn main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED="1"

[program:retover-celery]
directory=%(here)s
command=celery -A app.workers.celery_app:celery_app worker -l INFO
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED="1"
