"""Master abc_choice question catalog for WA Survey industry templates."""

from __future__ import annotations

# Each entry: industry slug (from INDUSTRY_CATALOG), industry display name, list of questions
# Each question: {"name": str, "body": str, "options": [str, str, str]}

WA_SURVEY_ABC_CATALOG: list[dict] = [
    {
        "slug": "healthcare_dental",
        "name": "Healthcare & Dental",
        "questions": [
            {"name": "Post-visit satisfaction", "body": "😊 Overall, how satisfied were you with your recent visit?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Wait time rating", "body": "⏱️ Following your recent visit, how would you rate the time you waited before being seen?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Staff attitude", "body": "🤝 Following your recent visit, how would you describe the attitude and helpfulness of our staff?", "options": ["Unfriendly", "Polite", "Very warm & caring"]},
            {"name": "Cleanliness", "body": "🧼 Following your recent visit, how would you rate the cleanliness of our facility?", "options": ["Needs improvement", "Clean", "Very clean & hygienic"]},
            {"name": "Treatment outcome", "body": "🩺 Following your recent visit, how satisfied are you with the result of your treatment?", "options": ["Dissatisfied", "Satisfied", "Exceeded expectations"]},
            {"name": "Pricing fairness", "body": "💰 Following your recent visit, do you feel our pricing is fair for the care you received?", "options": ["Too high", "Reasonable", "Very fair"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Visit met your needs", "body": "✅ Following your recent visit, did our service meet your needs today?", "options": ["Unlikely", "Possibly", "Definitely yes"]},
            {"name": "Booking experience", "body": "📅 Following your recent visit, how easy was it to book your appointment?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Communication clarity", "body": "💬 Following your recent visit, did our team clearly explain your condition and next steps?", "options": ["No", "Somewhat", "Yes, very clearly"]},
            {"name": "Appointment availability", "body": "🗓️ Following your recent visit, how convenient were the available appointment times?", "options": ["Not convenient", "Convenient", "Very flexible"]},
            {"name": "Pain management satisfaction", "body": "🩹 Following your recent visit, were you satisfied with how your pain or discomfort was managed?", "options": ["No", "Somewhat", "Yes, completely"]},
            {"name": "Explanation of treatment", "body": "📋 Following your recent visit, how well did the provider explain your treatment before starting?", "options": ["Not explained", "Somewhat explained", "Explained very well"]},
            {"name": "Waiting area comfort", "body": "🛋️ Following your recent visit, how comfortable was our waiting area?", "options": ["Uncomfortable", "Comfortable", "Very comfortable"]},
            {"name": "Reception staff rating", "body": "⭐ Following your recent visit, how would you rate our reception team's professionalism?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Follow-up care quality", "body": "📞 Following your recent visit, how satisfied are you with the follow-up care after your visit?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Hygienist satisfaction", "body": "😁 Following your recent visit, were you satisfied with the hygienist's care and approach?", "options": ["No", "Yes", "Yes, outstanding"]},
            {"name": "Parking & accessibility", "body": "🚗 Following your recent visit, how convenient was parking and access to our clinic?", "options": ["Difficult", "Fine", "Very easy"]},
            {"name": "Online/app experience", "body": "📱 Following your recent visit, how would you rate your experience with our online portal or app?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Overall care rating", "body": "🏥 Following your recent visit, overall, how would you rate the quality of care you received?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "recruitment_staffing",
        "name": "Recruitment & Staffing",
        "questions": [
            {"name": "Candidate experience", "body": "🎯 Following your recent visit, how would you rate your overall experience as a candidate with us?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Interview process rating", "body": "📝 Following your recent visit, how well organised and fair was our interview process?", "options": ["Disorganised", "Good", "Very smooth & fair"]},
            {"name": "Consultant rating", "body": "🤝 Following your recent visit, how would you rate the consultant who worked with you?", "options": ["Unhelpful", "Helpful", "Outstanding"]},
            {"name": "Placement satisfaction", "body": "💼 Following your recent visit, how satisfied are you with the placement you received?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Communication quality", "body": "💬 Following your recent visit, how would you rate the quality of communication throughout?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Employer satisfaction", "body": "🏢 Following your recent visit, (for employers) how satisfied are you with candidates provided?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Speed of placement", "body": "⚡ Following your recent visit, how would you rate the speed from brief to placement?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Professionalism", "body": "🎩 Following your recent visit, how professional did you find our team?", "options": ["Unprofessional", "Professional", "Highly professional"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Job match quality", "body": "🎯 Following your recent visit, how well did the role match your skills and expectations?", "options": ["Poor match", "Good match", "Perfect match"]},
            {"name": "CV support quality", "body": "📄 Following your recent visit, how helpful was the cv or application support provided?", "options": ["Not helpful", "Helpful", "Very helpful"]},
            {"name": "Onboarding support", "body": "🛠️ Following your recent visit, how well did we support you during onboarding?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Candidate quality (employer)", "body": "⭐ Following your recent visit, (for employers) how would you rate the quality of candidates?", "options": ["Below average", "Good", "Excellent"]},
            {"name": "Time-to-hire satisfaction", "body": "⏱️ Following your recent visit, were you satisfied with the time taken to hire?", "options": ["No, too long", "Acceptable", "Yes, very efficient"]},
            {"name": "Post-placement check-in", "body": "📞 Following your recent visit, how satisfied were you with post-placement follow-ups?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Salary negotiation support", "body": "💷 Following your recent visit, how effective was our support with salary negotiation?", "options": ["Not effective", "Effective", "Very effective"]},
            {"name": "Interview preparation quality", "body": "🎤 Following your recent visit, how useful was the interview preparation provided?", "options": ["Not useful", "Useful", "Very useful"]},
            {"name": "Transparency of process", "body": "🔍 Following your recent visit, how transparent was our process regarding roles and updates?", "options": ["Not transparent", "Transparent", "Completely transparent"]},
            {"name": "Long-term fit rating", "body": "📈 Following your recent visit, how well do you expect to fit in this role long-term?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Overall service rating", "body": "🌟 Following your recent visit, overall, how would you rate our recruitment service?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "hospitality_food",
        "name": "Hospitality & Food",
        "questions": [
            {"name": "Food quality", "body": "🍽️ Following your recent visit, how would you rate the quality of the food?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Service speed", "body": "⏱️ Following your recent visit, how would you rate the speed of service?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Staff friendliness", "body": "😊 Following your recent visit, how friendly and welcoming were our staff?", "options": ["Unfriendly", "Friendly", "Very warm & welcoming"]},
            {"name": "Cleanliness", "body": "🧼 Following your recent visit, how clean did you find our premises?", "options": ["Needs improvement", "Clean", "Spotless"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, do you feel you received good value for what you paid?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Ambience", "body": "🕯️ Following your recent visit, how would you rate the atmosphere and ambience?", "options": ["Unpleasant", "Pleasant", "Wonderful"]},
            {"name": "Booking experience", "body": "📅 Following your recent visit, how easy was it to make a booking?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Visit met your needs", "body": "✅ Following your recent visit, did our service meet your needs today?", "options": ["Unlikely", "Likely", "Very likely"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Portion size", "body": "🍝 Following your recent visit, how satisfied were you with the portion sizes?", "options": ["Too small", "Just right", "Generous"]},
            {"name": "Dietary/allergy handling", "body": "⚠️ Following your recent visit, how well did we accommodate dietary needs or allergies?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Drink quality", "body": "🥂 Following your recent visit, how would you rate the quality of drinks?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Menu variety", "body": "📖 Following your recent visit, how would you rate the variety of options on our menu?", "options": ["Limited", "Good variety", "Excellent variety"]},
            {"name": "Wait for table", "body": "🪑 Following your recent visit, how acceptable was the wait time for your table?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Bill accuracy", "body": "🧾 Following your recent visit, was your bill accurate and clear?", "options": ["No, issues", "Yes, accurate", "Yes, perfectly clear"]},
            {"name": "Noise level", "body": "🔊 Following your recent visit, how comfortable was the noise level during your visit?", "options": ["Too loud", "Acceptable", "Perfect"]},
            {"name": "Outdoor seating experience", "body": "🌿 Following your recent visit, (if applicable) how was your outdoor seating experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Takeaway packaging", "body": "📦 Following your recent visit, how would you rate the takeaway packaging quality?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Delivery experience", "body": "🚚 Following your recent visit, how was your delivery experience (if applicable)?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Overall dining rating", "body": "🍴 Following your recent visit, overall, how would you rate your dining experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "hotel_accommodation",
        "name": "Hotel & Accommodation",
        "questions": [
            {"name": "Check-in experience", "body": "🛎️ Following your recent visit, how smooth and welcoming was your check-in?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Room cleanliness", "body": "🛏️ Following your recent visit, how clean was your room upon arrival?", "options": ["Not clean", "Clean", "Spotless"]},
            {"name": "Breakfast quality", "body": "🍳 Following your recent visit, how would you rate the breakfast offering?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Staff friendliness", "body": "😊 Following your recent visit, how friendly and helpful were our staff?", "options": ["Unfriendly", "Friendly", "Very warm & helpful"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, did you feel the stay was worth the price?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Noise & comfort", "body": "🔇 Following your recent visit, how comfortable and quiet was your room?", "options": ["Uncomfortable/noisy", "Comfortable", "Very peaceful"]},
            {"name": "Facilities rating", "body": "🏋️ Following your recent visit, how would you rate the hotel facilities (gym, pool, etc.)?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Visit met your needs", "body": "✅ Following your recent visit, did our service meet your needs today?", "options": ["Unlikely", "Likely", "Definitely yes"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Check-out experience", "body": "🚪 Following your recent visit, how efficient and pleasant was your check-out?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Room temperature control", "body": "🌡️ Following your recent visit, how satisfied were you with room temperature control?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Wi-Fi quality", "body": "📶 Following your recent visit, how would you rate the wi-fi speed and reliability?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Bed comfort", "body": "🛌 Following your recent visit, how comfortable was your bed and pillows?", "options": ["Uncomfortable", "Comfortable", "Very comfortable"]},
            {"name": "Bathroom cleanliness", "body": "🚿 Following your recent visit, how clean was your bathroom?", "options": ["Not clean", "Clean", "Spotless"]},
            {"name": "Parking experience", "body": "🅿️ Following your recent visit, how convenient was parking at the hotel?", "options": ["Difficult", "Fine", "Very easy"]},
            {"name": "Concierge/help desk rating", "body": "🎫 Following your recent visit, how helpful was our concierge or help desk?", "options": ["Not helpful", "Helpful", "Very helpful"]},
            {"name": "Pool/gym facilities", "body": "🏊 Following your recent visit, how would you rate the pool or gym facilities?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "In-room dining", "body": "🍽️ Following your recent visit, how satisfied were you with in-room dining (if used)?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Evening turndown service", "body": "🌙 Following your recent visit, how would you rate the turndown service (if applicable)?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Overall stay rating", "body": "🏨 Following your recent visit, overall, how would you rate your stay with us?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "property_lettings",
        "name": "Property & Lettings",
        "questions": [
            {"name": "Viewing experience", "body": "🔑 Following your recent visit, how would you rate your property viewing experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Move-in condition", "body": "🏠 Following your recent visit, how satisfied were you with the condition of the property at move-in?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Maintenance response", "body": "🛠️ Following your recent visit, how quickly and effectively were maintenance issues addressed?", "options": ["Slow/poor", "Acceptable", "Fast & effective"]},
            {"name": "Communication", "body": "💬 Following your recent visit, how would you rate communication with our team?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, do you feel the rent is fair for the property?", "options": ["Too high", "Fair", "Very good value"]},
            {"name": "Property management", "body": "📋 Following your recent visit, how satisfied are you with overall property management?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Tenancy needs met", "body": "📋 Following your recent tenancy interaction, did our service meet your needs?", "options": ["Unlikely", "Unsure", "Yes, likely"]},
            {"name": "Agent professionalism", "body": "👔 Following your recent visit, how professional were our agents throughout?", "options": ["Unprofessional", "Professional", "Highly professional"]},
            {"name": "Issue resolution", "body": "⚙️ Following your recent visit, how satisfied were you with how issues were resolved?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Safety & security perception", "body": "🛡️ Following your recent visit, do you feel safe and secure in the property?", "options": ["No", "Somewhat", "Yes, completely"]},
            {"name": "Deposit handling", "body": "💰 Following your recent visit, how transparent and fair was deposit handling?", "options": ["Poor", "Fair", "Excellent"]},
            {"name": "Inventory accuracy", "body": "📄 Following your recent visit, was the inventory report accurate and complete?", "options": ["No", "Mostly", "Yes, perfect"]},
            {"name": "Move-out process", "body": "🚪 Following your recent visit, how smooth was the move-out process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Tenant communication quality", "body": "📱 Following your recent visit, how satisfied are you with our digital/email/phone updates?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Emergency response speed", "body": "🚨 Following your recent visit, how fast was the response to emergencies?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Online portal experience", "body": "💻 Following your recent visit, how would you rate our online tenant portal?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Referencing process", "body": "📝 Following your recent visit, how smooth was the referencing and application process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Rent review fairness", "body": "📈 Following your recent visit, do you feel rent reviews have been fair?", "options": ["Unfair", "Fair", "Very fair"]},
            {"name": "Overall tenancy rating", "body": "🏘️ Following your recent visit, overall, how would you rate your tenancy experience with us?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "retail_ecommerce",
        "name": "Retail & E-Commerce",
        "questions": [
            {"name": "Product quality", "body": "📦 Following your recent visit, how would you rate the quality of the product you received?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Delivery experience", "body": "🚚 Following your recent visit, how would you rate your delivery experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Packaging quality", "body": "📦 Following your recent visit, was your order packaged securely and attractively?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Returns process", "body": "🔄 Following your recent visit, how easy and clear was the returns process (if used)?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, do you feel you received good value for your purchase?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Staff helpfulness", "body": "👩‍💼 Following your recent visit, how helpful were our staff (in-store or online chat)?", "options": ["Unhelpful", "Helpful", "Very helpful"]},
            {"name": "Stock availability", "body": "📊 Following your recent visit, were the items you wanted in stock?", "options": ["Rarely", "Sometimes", "Always or almost always"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Purchase met your needs", "body": "✅ Following your recent order, did your purchase meet your needs today?", "options": ["Unlikely", "Maybe", "Definitely yes"]},
            {"name": "Website experience", "body": "💻 Following your recent visit, how easy was it to navigate our website?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Order accuracy", "body": "✅ Following your recent visit, was your order complete and accurate?", "options": ["No, issues", "Yes, accurate", "Yes, perfect"]},
            {"name": "Delivery speed", "body": "⏱️ Following your recent visit, how would you rate delivery speed?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Checkout experience", "body": "🛒 Following your recent visit, how smooth was the checkout process?", "options": ["Frustrating", "Smooth", "Very smooth"]},
            {"name": "Product description accuracy", "body": "📝 Following your recent visit, did the product match its online description?", "options": ["No", "Mostly", "Yes, perfectly"]},
            {"name": "Customer service rating", "body": "🎧 Following your recent visit, how would you rate our customer service team?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Checkout clarity", "body": "🧾 Following your recent purchase, how clear was the checkout process today?", "options": ["Not valuable", "Valuable", "Very valuable"]},
            {"name": "In-store experience", "body": "🏬 Following your recent visit, (if applicable) how was your in-store experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Click & collect experience", "body": "📱 Following your recent visit, how was your click & collect experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Refund speed", "body": "💸 Following your recent visit, how fast was your refund processed (if applicable)?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Overall shopping rating", "body": "🛍️ Following your recent visit, overall, how would you rate your shopping experience with us?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "automotive",
        "name": "Automotive",
        "questions": [
            {"name": "Work quality", "body": "🔧 Following your recent visit, how would you rate the quality of the work carried out?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Explanation of work", "body": "📋 Following your recent visit, did the team clearly explain what work was needed?", "options": ["No", "Somewhat", "Yes, very clearly"]},
            {"name": "Punctuality", "body": "⏰ Following your recent visit, was your vehicle ready when promised?", "options": ["No, late", "On time", "Earlier than expected"]},
            {"name": "Pricing transparency", "body": "💰 Following your recent visit, were prices explained clearly before work began?", "options": ["No", "Mostly", "Yes, fully transparent"]},
            {"name": "Vehicle cleanliness", "body": "🚗 Following your recent visit, how clean was your vehicle after service?", "options": ["Not clean", "Clean", "Spotless"]},
            {"name": "Booking experience", "body": "📅 Following your recent visit, how easy was it to book your service or repair?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Staff attitude", "body": "😊 Following your recent visit, how would you rate the attitude of our staff?", "options": ["Unfriendly", "Polite", "Very helpful & friendly"]},
            {"name": "Value for money", "body": "💷 Following your recent visit, do you feel the service was good value for money?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Turnaround time", "body": "⏱️ Following your recent visit, how satisfied were you with the time taken to complete work?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "MOT experience", "body": "📄 Following your recent visit, (if applicable) how was your mot experience with us?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Courtesy car availability", "body": "🚙 Following your recent visit, was a courtesy car available when needed (if applicable)?", "options": ["No", "Yes", "Yes, very convenient"]},
            {"name": "Parts quality", "body": "🔩 Following your recent visit, how would you rate the quality of parts used?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Diagnostic accuracy", "body": "🩺 Following your recent visit, did the team correctly diagnose the issue first time?", "options": ["No", "Yes", "Yes, impressively"]},
            {"name": "Invoice clarity", "body": "🧾 Following your recent visit, was your invoice clear and itemised?", "options": ["Unclear", "Clear", "Very clear & detailed"]},
            {"name": "Warranty handling", "body": "🛡️ Following your recent visit, how satisfied were you with warranty handling (if applicable)?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Collection/drop-off experience", "body": "🚘 Following your recent visit, how convenient was collection and drop-off?", "options": ["Inconvenient", "Fine", "Very convenient"]},
            {"name": "Upsell pressure rating", "body": "⚠️ Following your recent visit, did you feel pressured into additional work?", "options": ["Yes, too much", "A little", "No, not at all"]},
            {"name": "Post-service follow-up", "body": "📞 Following your recent visit, how satisfied were you with follow-up after service?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Overall garage rating", "body": "🔧 Following your recent visit, overall, how would you rate our garage?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "education_training",
        "name": "Education & Training",
        "questions": [
            {"name": "Course quality", "body": "📚 Following your recent visit, how would you rate the overall quality of the course?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Trainer rating", "body": "👩‍🏫 Following your recent visit, how would you rate the trainer or instructor?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Learning outcome", "body": "🎓 Following your recent visit, did you achieve what you wanted from the course?", "options": ["No", "Mostly", "Yes, completely"]},
            {"name": "Facilities", "body": "🏫 Following your recent visit, how would you rate the learning facilities?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, do you feel the course was worth the cost?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Course material quality", "body": "📖 Following your recent visit, how would you rate the quality of course materials?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Booking experience", "body": "📅 Following your recent visit, how easy was it to book or enrol?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Support quality", "body": "🎧 Following your recent visit, how would you rate learner support from the team?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Visit met your needs", "body": "✅ Following your recent visit, did our service meet your needs today?", "options": ["Unlikely", "Maybe", "Definitely yes"]},
            {"name": "Post-course resources", "body": "📁 Following your recent visit, how useful were the post-course resources (if any)?", "options": ["Not useful", "Useful", "Very useful"]},
            {"name": "Group size satisfaction", "body": "👥 Following your recent visit, was the group size appropriate for learning?", "options": ["Too large", "Just right", "Perfect"]},
            {"name": "Pace of delivery", "body": "⏱️ Following your recent visit, how would you rate the pace of the course?", "options": ["Too slow/fast", "Just right", "Perfect"]},
            {"name": "Online learning experience", "body": "💻 Following your recent visit, (if applicable) how was the online learning experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Assessment fairness", "body": "📝 Following your recent visit, were assessments fair and clear?", "options": ["Unfair", "Fair", "Very fair"]},
            {"name": "Certificate/accreditation value", "body": "🎓 Following your recent visit, how valuable is the certificate or accreditation?", "options": ["Not valuable", "Valuable", "Very valuable"]},
            {"name": "Pre-course communication", "body": "📧 Following your recent visit, how clear was communication before the course started?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Trainer knowledge depth", "body": "🧠 Following your recent visit, how knowledgeable was the trainer?", "options": ["Basic", "Good", "Highly expert"]},
            {"name": "Practical vs theory balance", "body": "⚖️ Following your recent visit, was the balance of practical and theory content right?", "options": ["Off balance", "Good", "Perfect"]},
            {"name": "Overall course rating", "body": "🏆 Following your recent visit, overall, how would you rate this course?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "legal_accountancy",
        "name": "Legal & Accountancy",
        "questions": [
            {"name": "Communication clarity", "body": "💬 Following your recent visit, how clearly did our team explain complex matters?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Matter handling", "body": "📂 Following your recent visit, how satisfied were you with how your case or matter was handled?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, do you feel fees were fair for the service provided?", "options": ["Poor value", "Fair", "Excellent value"]},
            {"name": "Case/matter outcome", "body": "⚖️ Following your recent visit, were you satisfied with the final outcome?", "options": ["No", "Yes", "Exceeded expectations"]},
            {"name": "Staff professionalism", "body": "👔 Following your recent visit, how professional were our staff throughout?", "options": ["Unprofessional", "Professional", "Highly professional"]},
            {"name": "Response time", "body": "⏱️ Following your recent visit, how quickly did we respond to your queries?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Onboarding experience", "body": "📝 Following your recent visit, how smooth was the initial onboarding or instruction process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Billing transparency", "body": "🧾 Following your recent visit, were your bills clear and explained?", "options": ["No", "Mostly", "Yes, fully transparent"]},
            {"name": "Service satisfaction today", "body": "😊 Following your recent visit, how satisfied are you with our service today?", "options": ["Unlikely", "Likely", "Very likely"]},
            {"name": "Expectation vs outcome", "body": "🎯 Following your recent visit, did the final outcome match what was promised or expected?", "options": ["No", "Mostly", "Yes, perfectly"]},
            {"name": "Document handling", "body": "📄 Following your recent visit, how satisfied were you with document management and security?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Jargon avoidance", "body": "🗣️ Following your recent visit, did the team avoid legal or technical jargon when speaking with you?", "options": ["No", "Sometimes", "Yes, always"]},
            {"name": "Deadline adherence", "body": "⏰ Following your recent visit, were all deadlines met by our team?", "options": ["No", "Mostly", "Yes, always"]},
            {"name": "Partner/senior access", "body": "👩‍⚖️ Following your recent visit, could you access senior team members when needed?", "options": ["No", "Sometimes", "Yes, easily"]},
            {"name": "Digital tools experience", "body": "💻 Following your recent visit, how would you rate our online portal or digital tools?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Tax return satisfaction", "body": "📑 Following your recent visit, (if applicable) how satisfied were you with tax return handling?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Court/hearing preparation", "body": "⚖️ Following your recent visit, (if applicable) how well prepared were you for court or hearing?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Confidentiality confidence", "body": "🔒 Following your recent visit, do you trust us to keep your information confidential?", "options": ["No", "Somewhat", "Yes, completely"]},
            {"name": "Overall service rating", "body": "🌟 Following your recent visit, overall, how would you rate our legal or accountancy service?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "fitness_wellness",
        "name": "Fitness & Wellness",
        "questions": [
            {"name": "Session quality", "body": "💪 Following your recent visit, how would you rate the quality of your session or class?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Trainer attitude", "body": "🧘 Following your recent visit, how motivating and supportive was the trainer?", "options": ["Unmotivating", "Good", "Very motivating & supportive"]},
            {"name": "Facilities rating", "body": "🏋️ Following your recent visit, how would you rate our facilities and equipment?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Cleanliness", "body": "🧼 Following your recent visit, how clean did you find our studio or gym?", "options": ["Needs improvement", "Clean", "Spotless"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, do you feel your membership or session was good value?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Class variety", "body": "📅 Following your recent visit, how satisfied are you with the variety of classes offered?", "options": ["Limited", "Good variety", "Excellent variety"]},
            {"name": "Booking experience", "body": "📱 Following your recent visit, how easy was it to book a session or class?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Staff friendliness", "body": "😊 Following your recent visit, how friendly and welcoming were our staff?", "options": ["Unfriendly", "Friendly", "Very warm & welcoming"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Membership value", "body": "🏷️ Following your recent visit, how would you rate the value of your membership plan?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Equipment availability", "body": "🏋️‍♂️ Following your recent visit, was equipment readily available when you needed it?", "options": ["Rarely", "Sometimes", "Always"]},
            {"name": "Changing room quality", "body": "🚿 Following your recent visit, how would you rate changing room and shower facilities?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "App/online portal rating", "body": "📲 Following your recent visit, how would you rate our app or online booking system?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Personal training value", "body": "🎯 Following your recent visit, (if applicable) how valuable was your personal training?", "options": ["Not valuable", "Valuable", "Very valuable"]},
            {"name": "Class size satisfaction", "body": "👥 Following your recent visit, was the class size comfortable and effective?", "options": ["Too crowded", "Good", "Perfect"]},
            {"name": "Parking & access", "body": "🅿️ Following your recent visit, how convenient was parking and access to our venue?", "options": ["Difficult", "Fine", "Very easy"]},
            {"name": "Nutrition/supplement advice", "body": "🥗 Following your recent visit, (if applicable) how helpful was nutrition or supplement advice?", "options": ["Not helpful", "Helpful", "Very helpful"]},
            {"name": "Injury support handling", "body": "🩹 Following your recent visit, how well did staff support you with an injury or limitation?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Peak time crowding", "body": "⏰ Following your recent visit, how do you find crowding during peak hours?", "options": ["Too crowded", "Acceptable", "Well managed"]},
            {"name": "Overall experience rating", "body": "🌟 Following your recent visit, overall, how would you rate your fitness & wellness experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "financial_services",
        "name": "Financial Services",
        "questions": [
            {"name": "Advice clarity", "body": "💡 Following your recent visit, how clear and understandable was the advice given?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Product suitability", "body": "📋 Following your recent visit, was the recommended product suitable for your needs?", "options": ["No", "Yes", "Yes, perfectly matched"]},
            {"name": "Adviser professionalism", "body": "👔 Following your recent visit, how professional was your adviser?", "options": ["Unprofessional", "Professional", "Highly professional"]},
            {"name": "Response time", "body": "⏱️ Following your recent visit, how quickly did we respond to your queries?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, do you feel fees or charges were fair?", "options": ["Poor value", "Fair", "Excellent value"]},
            {"name": "Onboarding experience", "body": "📝 Following your recent visit, how smooth was the onboarding or application process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Communication quality", "body": "💬 Following your recent visit, how would you rate ongoing communication from us?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Trust & confidence", "body": "🔒 Following your recent visit, do you feel confident and trusting in our advice?", "options": ["No", "Somewhat", "Yes, completely"]},
            {"name": "Compliance & transparency", "body": "📄 Following your recent visit, were all terms, risks, and costs explained transparently?", "options": ["No", "Mostly", "Yes, fully"]},
            {"name": "Digital platform rating", "body": "💻 Following your recent visit, how would you rate our online banking or portal?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Application process", "body": "📑 Following your recent visit, how easy was completing the application?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Mortgage/loan handling", "body": "🏠 Following your recent visit, (if applicable) how satisfied were you with mortgage or loan handling?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Claims experience", "body": "🛡️ Following your recent visit, (if applicable) how was your claims experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Renewal process", "body": "🔄 Following your recent visit, how smooth was the renewal process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Documentation clarity", "body": "📄 Following your recent visit, were all documents clear and easy to understand?", "options": ["No", "Mostly", "Yes, very clear"]},
            {"name": "Fee transparency", "body": "💰 Following your recent visit, were all fees disclosed upfront?", "options": ["No", "Mostly", "Yes, fully"]},
            {"name": "Switch/transfer experience", "body": "🔄 Following your recent visit, how smooth was switching or transferring to us?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Complaint handling", "body": "🎧 Following your recent visit, (if applicable) how well was your complaint handled?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Overall service rating", "body": "🌟 Following your recent visit, overall, how would you rate our financial service?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "logistics_delivery",
        "name": "Logistics & Delivery",
        "questions": [
            {"name": "Delivery speed", "body": "⚡ Following your recent visit, how would you rate the speed of delivery?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Packaging condition", "body": "📦 Following your recent visit, did your parcel arrive in good condition?", "options": ["Damaged", "Good", "Perfect condition"]},
            {"name": "Driver attitude", "body": "🚛 Following your recent visit, how friendly and professional was the driver?", "options": ["Unfriendly", "Polite", "Very friendly & helpful"]},
            {"name": "Delivery accuracy", "body": "✅ Following your recent visit, was your delivery made to the correct address and safe place?", "options": ["No", "Yes", "Yes, with care"]},
            {"name": "Communication/tracking", "body": "📍 Following your recent visit, how accurate and useful was the tracking information?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Collection experience", "body": "🏢 Following your recent visit, (if applicable) how was your collection experience from depot?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Returns process", "body": "🔄 Following your recent visit, how easy was the returns process (if used)?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, do you feel delivery pricing was fair?", "options": ["Too high", "Fair", "Very good value"]},
            {"name": "Delivery met your needs", "body": "✅ Following your recent delivery, did the service meet your needs today?", "options": ["Unlikely", "Likely", "Definitely yes"]},
            {"name": "Safe place delivery rating", "body": "🏠 Following your recent visit, (if applicable) how satisfied were you with safe place instructions followed?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Missed delivery handling", "body": "📝 Following your recent visit, how well was a missed delivery handled?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Customer service quality", "body": "🎧 Following your recent visit, how would you rate our customer service team?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "App/portal experience", "body": "📱 Following your recent visit, how would you rate our app or tracking portal?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Proof of delivery satisfaction", "body": "📸 Following your recent visit, was proof of delivery clear and timely?", "options": ["No", "Yes", "Yes, with photo & time"]},
            {"name": "Fragile item handling", "body": "⚠️ Following your recent visit, were fragile items handled with care?", "options": ["No", "Yes", "Yes, clearly well protected"]},
            {"name": "Same-day service rating", "body": "⏱️ Following your recent visit, (if applicable) how satisfied were you with same-day delivery?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "International delivery rating", "body": "🌍 Following your recent visit, (if applicable) how was your international delivery experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Business account experience", "body": "🏢 Following your recent visit, (if applicable) how satisfied are you with our business account service?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Overall delivery rating", "body": "🚚 Following your recent visit, overall, how would you rate our delivery service?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "events_entertainment",
        "name": "Events & Entertainment",
        "questions": [
            {"name": "Event organisation", "body": "🎪 Following your recent visit, how well organised was the event overall?", "options": ["Poorly", "Well", "Very well organised"]},
            {"name": "Venue quality", "body": "🏟️ Following your recent visit, how would you rate the venue?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Staff friendliness", "body": "😊 Following your recent visit, how friendly and helpful were event staff?", "options": ["Unfriendly", "Friendly", "Very warm & helpful"]},
            {"name": "Value for money", "body": "💰 Following your recent visit, did the event feel worth the ticket price?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Overall service satisfaction", "body": "😊 Following your recent visit, how satisfied are you with the service you received today?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Visit met your needs", "body": "✅ Following your recent visit, did our service meet your needs today?", "options": ["Unlikely", "Likely", "Definitely yes"]},
            {"name": "Ticketing/booking experience", "body": "🎟️ Following your recent visit, how easy was it to book tickets?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Queue management", "body": "🚶 Following your recent visit, how well were queues managed at entry or bars?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Food & drink quality", "body": "🍔 Following your recent visit, how would you rate the food and drink options?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Parking & transport", "body": "🅿️ Following your recent visit, how convenient was parking or public transport access?", "options": ["Difficult", "Fine", "Very easy"]},
            {"name": "Safety & security feel", "body": "🛡️ Following your recent visit, did you feel safe and secure throughout?", "options": ["No", "Yes", "Yes, very well managed"]},
            {"name": "Speaker/performer rating", "body": "🎤 Following your recent visit, how would you rate the speaker, performer, or act?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Sound & AV quality", "body": "🔊 Following your recent visit, how clear and professional was the sound and av?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Networking opportunity", "body": "🤝 Following your recent visit, how valuable were the networking opportunities (if applicable)?", "options": ["Not valuable", "Valuable", "Very valuable"]},
            {"name": "Programme/schedule quality", "body": "📅 Following your recent visit, was the event schedule well paced and interesting?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Signage & navigation", "body": "🧭 Following your recent visit, was it easy to find your way around the venue?", "options": ["No", "Yes", "Yes, very clear"]},
            {"name": "Accessibility provision", "body": "♿ Following your recent visit, how well did the event accommodate accessibility needs?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Merchandise experience", "body": "🛍️ Following your recent visit, (if applicable) how was the merchandise buying experience?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Post-event communication", "body": "📧 Following your recent visit, how useful was any follow-up or post-event communication?", "options": ["Not useful", "Useful", "Very useful"]},
            {"name": "Overall event rating", "body": "🎉 Following your recent visit, overall, how would you rate this event?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
    {
        "slug": "employee_survey",
        "name": "Employee Survey",
        "questions": [
            {"name": "Morale", "body": "📈 Following your recent visit, how would you describe the current mood and spirit within our team?", "options": ["Low", "Moderate", "High"]},
            {"name": "Work-life balance", "body": "⚖️ Following your recent visit, how well are you able to separate work from personal time?", "options": ["Poorly", "Adequately", "Very well"]},
            {"name": "Feeling valued", "body": "💙 Following your recent visit, do you feel that your contributions are genuinely appreciated here?", "options": ["No", "Somewhat", "Yes, absolutely"]},
            {"name": "Workload", "body": "📊 Following your recent visit, how do you find your current volume of work?", "options": ["Overwhelming", "Manageable", "Too light"]},
            {"name": "Motivation", "body": "🔥 Following your recent visit, how energized and driven do you feel to perform well in your role?", "options": ["Not motivated", "Moderately motivated", "Highly motivated"]},
            {"name": "Manager communication", "body": "🗣️ Following your recent visit, does your manager share information, feedback, and expectations clearly?", "options": ["Rarely", "Sometimes", "Consistently"]},
            {"name": "Manager fairness", "body": "⚖️ Following your recent visit, do you feel your manager treats all team members fairly and without favoritism?", "options": ["No", "Sometimes", "Yes, always"]},
            {"name": "Recognition", "body": "🏆 Following your recent visit, how often do you receive meaningful recognition for your efforts?", "options": ["Rarely or never", "Sometimes", "Regularly"]},
            {"name": "Team collaboration", "body": "🤝 Following your recent visit, how smoothly does your team share information and support one another?", "options": ["Poorly", "Well", "Excellently"]},
            {"name": "Inclusion & belonging", "body": "🌈 Following your recent visit, do you feel safe and welcome to be your authentic self at work?", "options": ["No", "Sometimes", "Yes, fully"]},
            {"name": "Career progression", "body": "📈 Following your recent visit, are you satisfied with the opportunities to grow and advance here?", "options": ["No", "Neutral", "Yes"]},
            {"name": "Training quality", "body": "📚 Following your recent visit, how useful and relevant is the training you receive for your job?", "options": ["Not useful", "Somewhat useful", "Very useful"]},
            {"name": "Goal clarity", "body": "🎯 Following your recent visit, do you clearly understand your most important work goals right now?", "options": ["No", "Partially", "Yes, clearly"]},
            {"name": "Role clarity", "body": "📄 Following your recent visit, do you have a clear understanding of your daily responsibilities and expectations?", "options": ["No", "Partly", "Yes, very clear"]},
            {"name": "Job satisfaction", "body": "😊 Following your recent visit, overall, how content are you with your current role and daily work?", "options": ["Dissatisfied", "Neutral", "Satisfied"]},
            {"name": "Internal communication", "body": "📢 Following your recent visit, how effective is the flow of company news and important updates?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Pay & benefits fairness", "body": "💰 Following your recent visit, do you believe your total compensation is fair compared to your role and effort?", "options": ["No", "Neutral", "Yes"]},
            {"name": "Remote/hybrid flexibility", "body": "🏡 Following your recent visit, does your current work arrangement give you the flexibility you need?", "options": ["No", "Partially", "Yes, fully"]},
            {"name": "Psychological safety", "body": "🛡️ Following your recent visit, can you speak up with concerns or new ideas without fear of negative consequences?", "options": ["No", "Sometimes", "Yes, confidently"]},
            {"name": "Overall employee experience", "body": "🌟 Following your recent visit, how would you rate this company as a place to work, all things considered?", "options": ["Excellent", "Good", "Poor"]},
            {"name": "Issue resolution rating", "body": "⚙️ Following your recent visit, how satisfied were you with how any issue was handled?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Information clarity", "body": "💬 Following your recent visit, how clear was the information provided to you?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Hand-off wait time", "body": "⏱️ Following your recent visit, how acceptable was your wait or hand-off time?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Facility access comfort", "body": "🚪 Following your recent visit, how comfortable was access to our facility?", "options": ["Difficult", "Comfortable", "Very easy"]},
            {"name": "Overall experience today", "body": "🌟 Following your recent visit, how would you rate your overall experience today?", "options": ["Excellent", "Good", "Poor"]},
        ],
    },
]
