"""Master abc_choice question catalog for WA Survey industry templates."""

from __future__ import annotations

# Each entry: industry slug (from INDUSTRY_CATALOG), industry display name, list of questions
# Each question: {"name": str, "body": str, "options": [str, str, str]}

WA_SURVEY_ABC_CATALOG: list[dict] = [
    {
        "slug": "healthcare_dental",
        "name": "Healthcare & Dental",
        "questions": [
            {"name": "Post-visit satisfaction", "body": "😊 Overall, how satisfied were you with your recent visit?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Wait time rating", "body": "⏱️ How would you rate the time you waited before being seen?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Staff attitude", "body": "🤝 How would you describe the attitude and helpfulness of our staff?", "options": ["Unfriendly", "Polite", "Very warm & caring"]},
            {"name": "Cleanliness", "body": "🧼 How would you rate the cleanliness of our facility?", "options": ["Needs improvement", "Clean", "Very clean & hygienic"]},
            {"name": "Treatment outcome", "body": "🩺 How satisfied are you with the result of your treatment?", "options": ["Dissatisfied", "Satisfied", "Exceeded expectations"]},
            {"name": "Pricing fairness", "body": "💰 Do you feel our pricing is fair for the care you received?", "options": ["Too high", "Reasonable", "Very fair"]},
            {"name": "Would recommend", "body": "📢 Would you recommend our clinic to family or friends?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Return intent", "body": "🔄 Would you choose our clinic again for future care?", "options": ["Unlikely", "Possibly", "Definitely yes"]},
            {"name": "Booking experience", "body": "📅 How easy was it to book your appointment?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Communication clarity", "body": "💬 Did our team clearly explain your condition and next steps?", "options": ["No", "Somewhat", "Yes, very clearly"]},
            {"name": "Appointment availability", "body": "🗓️ How convenient were the available appointment times?", "options": ["Not convenient", "Convenient", "Very flexible"]},
            {"name": "Pain management satisfaction", "body": "🩹 Were you satisfied with how your pain or discomfort was managed?", "options": ["No", "Somewhat", "Yes, completely"]},
            {"name": "Explanation of treatment", "body": "📋 How well did the provider explain your treatment before starting?", "options": ["Not explained", "Somewhat explained", "Explained very well"]},
            {"name": "Waiting area comfort", "body": "🛋️ How comfortable was our waiting area?", "options": ["Uncomfortable", "Comfortable", "Very comfortable"]},
            {"name": "Reception staff rating", "body": "⭐ How would you rate our reception team's professionalism?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Follow-up care quality", "body": "📞 How satisfied are you with the follow-up care after your visit?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Hygienist satisfaction", "body": "😁 Were you satisfied with the hygienist's care and approach?", "options": ["No", "Yes", "Yes, outstanding"]},
            {"name": "Parking & accessibility", "body": "🚗 How convenient was parking and access to our clinic?", "options": ["Difficult", "Fine", "Very easy"]},
            {"name": "Online/app experience", "body": "📱 How would you rate your experience with our online portal or app?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Overall care rating", "body": "🏥 Overall, how would you rate the quality of care you received?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "recruitment_staffing",
        "name": "Recruitment & Staffing",
        "questions": [
            {"name": "Candidate experience", "body": "🎯 How would you rate your overall experience as a candidate with us?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Interview process rating", "body": "📝 How well organised and fair was our interview process?", "options": ["Disorganised", "Good", "Very smooth & fair"]},
            {"name": "Consultant rating", "body": "🤝 How would you rate the consultant who worked with you?", "options": ["Unhelpful", "Helpful", "Outstanding"]},
            {"name": "Placement satisfaction", "body": "💼 How satisfied are you with the placement you received?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Communication quality", "body": "💬 How would you rate the quality of communication throughout?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Employer satisfaction", "body": "🏢 (For employers) How satisfied are you with candidates provided?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Speed of placement", "body": "⚡ How would you rate the speed from brief to placement?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Professionalism", "body": "🎩 How professional did you find our team?", "options": ["Unprofessional", "Professional", "Highly professional"]},
            {"name": "Would recommend", "body": "📢 Would you recommend our services to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Job match quality", "body": "🎯 How well did the role match your skills and expectations?", "options": ["Poor match", "Good match", "Perfect match"]},
            {"name": "CV support quality", "body": "📄 How helpful was the CV or application support provided?", "options": ["Not helpful", "Helpful", "Very helpful"]},
            {"name": "Onboarding support", "body": "🛠️ How well did we support you during onboarding?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Candidate quality (employer)", "body": "⭐ (For employers) How would you rate the quality of candidates?", "options": ["Below average", "Good", "Excellent"]},
            {"name": "Time-to-hire satisfaction", "body": "⏱️ Were you satisfied with the time taken to hire?", "options": ["No, too long", "Acceptable", "Yes, very efficient"]},
            {"name": "Post-placement check-in", "body": "📞 How satisfied were you with post-placement follow-ups?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Salary negotiation support", "body": "💷 How effective was our support with salary negotiation?", "options": ["Not effective", "Effective", "Very effective"]},
            {"name": "Interview preparation quality", "body": "🎤 How useful was the interview preparation provided?", "options": ["Not useful", "Useful", "Very useful"]},
            {"name": "Transparency of process", "body": "🔍 How transparent was our process regarding roles and updates?", "options": ["Not transparent", "Transparent", "Completely transparent"]},
            {"name": "Long-term fit rating", "body": "📈 How well do you expect to fit in this role long-term?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Overall service rating", "body": "🌟 Overall, how would you rate our recruitment service?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "hospitality_food",
        "name": "Hospitality & Food",
        "questions": [
            {"name": "Food quality", "body": "🍽️ How would you rate the quality of the food?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Service speed", "body": "⏱️ How would you rate the speed of service?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Staff friendliness", "body": "😊 How friendly and welcoming were our staff?", "options": ["Unfriendly", "Friendly", "Very warm & welcoming"]},
            {"name": "Cleanliness", "body": "🧼 How clean did you find our premises?", "options": ["Needs improvement", "Clean", "Spotless"]},
            {"name": "Value for money", "body": "💰 Do you feel you received good value for what you paid?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Ambience", "body": "🕯️ How would you rate the atmosphere and ambience?", "options": ["Unpleasant", "Pleasant", "Wonderful"]},
            {"name": "Booking experience", "body": "📅 How easy was it to make a booking?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Return intent", "body": "🔄 How likely are you to dine with us again?", "options": ["Unlikely", "Likely", "Very likely"]},
            {"name": "Would recommend", "body": "📢 Would you recommend us to friends or family?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Portion size", "body": "🍝 How satisfied were you with the portion sizes?", "options": ["Too small", "Just right", "Generous"]},
            {"name": "Dietary/allergy handling", "body": "⚠️ How well did we accommodate dietary needs or allergies?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Drink quality", "body": "🥂 How would you rate the quality of drinks?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Menu variety", "body": "📖 How would you rate the variety of options on our menu?", "options": ["Limited", "Good variety", "Excellent variety"]},
            {"name": "Wait for table", "body": "🪑 How acceptable was the wait time for your table?", "options": ["Too long", "Acceptable", "Very short"]},
            {"name": "Bill accuracy", "body": "🧾 Was your bill accurate and clear?", "options": ["No, issues", "Yes, accurate", "Yes, perfectly clear"]},
            {"name": "Noise level", "body": "🔊 How comfortable was the noise level during your visit?", "options": ["Too loud", "Acceptable", "Perfect"]},
            {"name": "Outdoor seating experience", "body": "🌿 (If applicable) How was your outdoor seating experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Takeaway packaging", "body": "📦 How would you rate the takeaway packaging quality?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Delivery experience", "body": "🚚 How was your delivery experience (if applicable)?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Overall dining rating", "body": "🍴 Overall, how would you rate your dining experience?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "hotel_accommodation",
        "name": "Hotel & Accommodation",
        "questions": [
            {"name": "Check-in experience", "body": "🛎️ How smooth and welcoming was your check-in?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Room cleanliness", "body": "🛏️ How clean was your room upon arrival?", "options": ["Not clean", "Clean", "Spotless"]},
            {"name": "Breakfast quality", "body": "🍳 How would you rate the breakfast offering?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Staff friendliness", "body": "😊 How friendly and helpful were our staff?", "options": ["Unfriendly", "Friendly", "Very warm & helpful"]},
            {"name": "Value for money", "body": "💰 Did you feel the stay was worth the price?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Noise & comfort", "body": "🔇 How comfortable and quiet was your room?", "options": ["Uncomfortable/noisy", "Comfortable", "Very peaceful"]},
            {"name": "Facilities rating", "body": "🏋️ How would you rate the hotel facilities (gym, pool, etc.)?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Return intent", "body": "🔄 Would you stay with us again?", "options": ["Unlikely", "Likely", "Definitely yes"]},
            {"name": "Would recommend", "body": "📢 Would you recommend our hotel to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Check-out experience", "body": "🚪 How efficient and pleasant was your check-out?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Room temperature control", "body": "🌡️ How satisfied were you with room temperature control?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Wi-Fi quality", "body": "📶 How would you rate the Wi-Fi speed and reliability?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Bed comfort", "body": "🛌 How comfortable was your bed and pillows?", "options": ["Uncomfortable", "Comfortable", "Very comfortable"]},
            {"name": "Bathroom cleanliness", "body": "🚿 How clean was your bathroom?", "options": ["Not clean", "Clean", "Spotless"]},
            {"name": "Parking experience", "body": "🅿️ How convenient was parking at the hotel?", "options": ["Difficult", "Fine", "Very easy"]},
            {"name": "Concierge/help desk rating", "body": "🎫 How helpful was our concierge or help desk?", "options": ["Not helpful", "Helpful", "Very helpful"]},
            {"name": "Pool/gym facilities", "body": "🏊 How would you rate the pool or gym facilities?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "In-room dining", "body": "🍽️ How satisfied were you with in-room dining (if used)?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Evening turndown service", "body": "🌙 How would you rate the turndown service (if applicable)?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Overall stay rating", "body": "🏨 Overall, how would you rate your stay with us?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "property_lettings",
        "name": "Property & Lettings",
        "questions": [
            {"name": "Viewing experience", "body": "🔑 How would you rate your property viewing experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Move-in condition", "body": "🏠 How satisfied were you with the condition of the property at move-in?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Maintenance response", "body": "🛠️ How quickly and effectively were maintenance issues addressed?", "options": ["Slow/poor", "Acceptable", "Fast & effective"]},
            {"name": "Communication", "body": "💬 How would you rate communication with our team?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Value for money", "body": "💰 Do you feel the rent is fair for the property?", "options": ["Too high", "Fair", "Very good value"]},
            {"name": "Property management", "body": "📋 How satisfied are you with overall property management?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Would recommend", "body": "📢 Would you recommend our lettings service to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Renewal intent", "body": "🔄 Are you likely to renew your tenancy with us?", "options": ["Unlikely", "Unsure", "Yes, likely"]},
            {"name": "Agent professionalism", "body": "👔 How professional were our agents throughout?", "options": ["Unprofessional", "Professional", "Highly professional"]},
            {"name": "Issue resolution", "body": "⚙️ How satisfied were you with how issues were resolved?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Safety & security perception", "body": "🛡️ Do you feel safe and secure in the property?", "options": ["No", "Somewhat", "Yes, completely"]},
            {"name": "Deposit handling", "body": "💰 How transparent and fair was deposit handling?", "options": ["Poor", "Fair", "Excellent"]},
            {"name": "Inventory accuracy", "body": "📄 Was the inventory report accurate and complete?", "options": ["No", "Mostly", "Yes, perfect"]},
            {"name": "Move-out process", "body": "🚪 How smooth was the move-out process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Tenant communication quality", "body": "📱 How satisfied are you with our digital/email/phone updates?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Emergency response speed", "body": "🚨 How fast was the response to emergencies?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Online portal experience", "body": "💻 How would you rate our online tenant portal?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Referencing process", "body": "📝 How smooth was the referencing and application process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Rent review fairness", "body": "📈 Do you feel rent reviews have been fair?", "options": ["Unfair", "Fair", "Very fair"]},
            {"name": "Overall tenancy rating", "body": "🏘️ Overall, how would you rate your tenancy experience with us?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "retail_ecommerce",
        "name": "Retail & E-Commerce",
        "questions": [
            {"name": "Product quality", "body": "📦 How would you rate the quality of the product you received?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Delivery experience", "body": "🚚 How would you rate your delivery experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Packaging quality", "body": "📦 Was your order packaged securely and attractively?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Returns process", "body": "🔄 How easy and clear was the returns process (if used)?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Value for money", "body": "💰 Do you feel you received good value for your purchase?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Staff helpfulness", "body": "👩‍💼 How helpful were our staff (in-store or online chat)?", "options": ["Unhelpful", "Helpful", "Very helpful"]},
            {"name": "Stock availability", "body": "📊 Were the items you wanted in stock?", "options": ["Rarely", "Sometimes", "Always or almost always"]},
            {"name": "Would recommend", "body": "📢 Would you recommend us to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Repeat purchase intent", "body": "🔄 Are you likely to shop with us again?", "options": ["Unlikely", "Maybe", "Definitely yes"]},
            {"name": "Website experience", "body": "💻 How easy was it to navigate our website?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Order accuracy", "body": "✅ Was your order complete and accurate?", "options": ["No, issues", "Yes, accurate", "Yes, perfect"]},
            {"name": "Delivery speed", "body": "⏱️ How would you rate delivery speed?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Checkout experience", "body": "🛒 How smooth was the checkout process?", "options": ["Frustrating", "Smooth", "Very smooth"]},
            {"name": "Product description accuracy", "body": "📝 Did the product match its online description?", "options": ["No", "Mostly", "Yes, perfectly"]},
            {"name": "Customer service rating", "body": "🎧 How would you rate our customer service team?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Loyalty programme value", "body": "💎 How valuable do you find our loyalty programme?", "options": ["Not valuable", "Valuable", "Very valuable"]},
            {"name": "In-store experience", "body": "🏬 (If applicable) How was your in-store experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Click & collect experience", "body": "📱 How was your click & collect experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Refund speed", "body": "💸 How fast was your refund processed (if applicable)?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Overall shopping rating", "body": "🛍️ Overall, how would you rate your shopping experience with us?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "automotive",
        "name": "Automotive",
        "questions": [
            {"name": "Work quality", "body": "🔧 How would you rate the quality of the work carried out?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Explanation of work", "body": "📋 Did the team clearly explain what work was needed?", "options": ["No", "Somewhat", "Yes, very clearly"]},
            {"name": "Punctuality", "body": "⏰ Was your vehicle ready when promised?", "options": ["No, late", "On time", "Earlier than expected"]},
            {"name": "Pricing transparency", "body": "💰 Were prices explained clearly before work began?", "options": ["No", "Mostly", "Yes, fully transparent"]},
            {"name": "Vehicle cleanliness", "body": "🚗 How clean was your vehicle after service?", "options": ["Not clean", "Clean", "Spotless"]},
            {"name": "Booking experience", "body": "📅 How easy was it to book your service or repair?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Staff attitude", "body": "😊 How would you rate the attitude of our staff?", "options": ["Unfriendly", "Polite", "Very helpful & friendly"]},
            {"name": "Value for money", "body": "💷 Do you feel the service was good value for money?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Would recommend", "body": "📢 Would you recommend our garage to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Turnaround time", "body": "⏱️ How satisfied were you with the time taken to complete work?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "MOT experience", "body": "📄 (If applicable) How was your MOT experience with us?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Courtesy car availability", "body": "🚙 Was a courtesy car available when needed (if applicable)?", "options": ["No", "Yes", "Yes, very convenient"]},
            {"name": "Parts quality", "body": "🔩 How would you rate the quality of parts used?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Diagnostic accuracy", "body": "🩺 Did the team correctly diagnose the issue first time?", "options": ["No", "Yes", "Yes, impressively"]},
            {"name": "Invoice clarity", "body": "🧾 Was your invoice clear and itemised?", "options": ["Unclear", "Clear", "Very clear & detailed"]},
            {"name": "Warranty handling", "body": "🛡️ How satisfied were you with warranty handling (if applicable)?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Collection/drop-off experience", "body": "🚘 How convenient was collection and drop-off?", "options": ["Inconvenient", "Fine", "Very convenient"]},
            {"name": "Upsell pressure rating", "body": "⚠️ Did you feel pressured into additional work?", "options": ["Yes, too much", "A little", "No, not at all"]},
            {"name": "Post-service follow-up", "body": "📞 How satisfied were you with follow-up after service?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Overall garage rating", "body": "🔧 Overall, how would you rate our garage?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "education_training",
        "name": "Education & Training",
        "questions": [
            {"name": "Course quality", "body": "📚 How would you rate the overall quality of the course?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Trainer rating", "body": "👩‍🏫 How would you rate the trainer or instructor?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Learning outcome", "body": "🎓 Did you achieve what you wanted from the course?", "options": ["No", "Mostly", "Yes, completely"]},
            {"name": "Facilities", "body": "🏫 How would you rate the learning facilities?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Value for money", "body": "💰 Do you feel the course was worth the cost?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Course material quality", "body": "📖 How would you rate the quality of course materials?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Would recommend", "body": "📢 Would you recommend this course to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Booking experience", "body": "📅 How easy was it to book or enrol?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Support quality", "body": "🎧 How would you rate learner support from the team?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Return intent", "body": "🔄 Would you take another course with us?", "options": ["Unlikely", "Maybe", "Definitely yes"]},
            {"name": "Post-course resources", "body": "📁 How useful were the post-course resources (if any)?", "options": ["Not useful", "Useful", "Very useful"]},
            {"name": "Group size satisfaction", "body": "👥 Was the group size appropriate for learning?", "options": ["Too large", "Just right", "Perfect"]},
            {"name": "Pace of delivery", "body": "⏱️ How would you rate the pace of the course?", "options": ["Too slow/fast", "Just right", "Perfect"]},
            {"name": "Online learning experience", "body": "💻 (If applicable) How was the online learning experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Assessment fairness", "body": "📝 Were assessments fair and clear?", "options": ["Unfair", "Fair", "Very fair"]},
            {"name": "Certificate/accreditation value", "body": "🎓 How valuable is the certificate or accreditation?", "options": ["Not valuable", "Valuable", "Very valuable"]},
            {"name": "Pre-course communication", "body": "📧 How clear was communication before the course started?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Trainer knowledge depth", "body": "🧠 How knowledgeable was the trainer?", "options": ["Basic", "Good", "Highly expert"]},
            {"name": "Practical vs theory balance", "body": "⚖️ Was the balance of practical and theory content right?", "options": ["Off balance", "Good", "Perfect"]},
            {"name": "Overall course rating", "body": "🏆 Overall, how would you rate this course?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "legal_accountancy",
        "name": "Legal & Accountancy",
        "questions": [
            {"name": "Communication clarity", "body": "💬 How clearly did our team explain complex matters?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Matter handling", "body": "📂 How satisfied were you with how your case or matter was handled?", "options": ["Dissatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Value for money", "body": "💰 Do you feel fees were fair for the service provided?", "options": ["Poor value", "Fair", "Excellent value"]},
            {"name": "Case/matter outcome", "body": "⚖️ Were you satisfied with the final outcome?", "options": ["No", "Yes", "Exceeded expectations"]},
            {"name": "Staff professionalism", "body": "👔 How professional were our staff throughout?", "options": ["Unprofessional", "Professional", "Highly professional"]},
            {"name": "Response time", "body": "⏱️ How quickly did we respond to your queries?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Would recommend", "body": "📢 Would you recommend our firm to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Onboarding experience", "body": "📝 How smooth was the initial onboarding or instruction process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Billing transparency", "body": "🧾 Were your bills clear and explained?", "options": ["No", "Mostly", "Yes, fully transparent"]},
            {"name": "Referral likelihood", "body": "🔁 How likely are you to refer us to a colleague or friend?", "options": ["Unlikely", "Likely", "Very likely"]},
            {"name": "Expectation vs outcome", "body": "🎯 Did the final outcome match what was promised or expected?", "options": ["No", "Mostly", "Yes, perfectly"]},
            {"name": "Document handling", "body": "📄 How satisfied were you with document management and security?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Jargon avoidance", "body": "🗣️ Did the team avoid legal or technical jargon when speaking with you?", "options": ["No", "Sometimes", "Yes, always"]},
            {"name": "Deadline adherence", "body": "⏰ Were all deadlines met by our team?", "options": ["No", "Mostly", "Yes, always"]},
            {"name": "Partner/senior access", "body": "👩‍⚖️ Could you access senior team members when needed?", "options": ["No", "Sometimes", "Yes, easily"]},
            {"name": "Digital tools experience", "body": "💻 How would you rate our online portal or digital tools?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Tax return satisfaction", "body": "📑 (If applicable) How satisfied were you with tax return handling?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Court/hearing preparation", "body": "⚖️ (If applicable) How well prepared were you for court or hearing?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Confidentiality confidence", "body": "🔒 Do you trust us to keep your information confidential?", "options": ["No", "Somewhat", "Yes, completely"]},
            {"name": "Overall service rating", "body": "🌟 Overall, how would you rate our legal or accountancy service?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "fitness_wellness",
        "name": "Fitness & Wellness",
        "questions": [
            {"name": "Session quality", "body": "💪 How would you rate the quality of your session or class?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Trainer attitude", "body": "🧘 How motivating and supportive was the trainer?", "options": ["Unmotivating", "Good", "Very motivating & supportive"]},
            {"name": "Facilities rating", "body": "🏋️ How would you rate our facilities and equipment?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Cleanliness", "body": "🧼 How clean did you find our studio or gym?", "options": ["Needs improvement", "Clean", "Spotless"]},
            {"name": "Value for money", "body": "💰 Do you feel your membership or session was good value?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Class variety", "body": "📅 How satisfied are you with the variety of classes offered?", "options": ["Limited", "Good variety", "Excellent variety"]},
            {"name": "Booking experience", "body": "📱 How easy was it to book a session or class?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Staff friendliness", "body": "😊 How friendly and welcoming were our staff?", "options": ["Unfriendly", "Friendly", "Very warm & welcoming"]},
            {"name": "Would recommend", "body": "📢 Would you recommend us to a friend?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Membership value", "body": "🏷️ How would you rate the value of your membership plan?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Equipment availability", "body": "🏋️‍♂️ Was equipment readily available when you needed it?", "options": ["Rarely", "Sometimes", "Always"]},
            {"name": "Changing room quality", "body": "🚿 How would you rate changing room and shower facilities?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "App/online portal rating", "body": "📲 How would you rate our app or online booking system?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Personal training value", "body": "🎯 (If applicable) How valuable was your personal training?", "options": ["Not valuable", "Valuable", "Very valuable"]},
            {"name": "Class size satisfaction", "body": "👥 Was the class size comfortable and effective?", "options": ["Too crowded", "Good", "Perfect"]},
            {"name": "Parking & access", "body": "🅿️ How convenient was parking and access to our venue?", "options": ["Difficult", "Fine", "Very easy"]},
            {"name": "Nutrition/supplement advice", "body": "🥗 (If applicable) How helpful was nutrition or supplement advice?", "options": ["Not helpful", "Helpful", "Very helpful"]},
            {"name": "Injury support handling", "body": "🩹 How well did staff support you with an injury or limitation?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Peak time crowding", "body": "⏰ How do you find crowding during peak hours?", "options": ["Too crowded", "Acceptable", "Well managed"]},
            {"name": "Overall experience rating", "body": "🌟 Overall, how would you rate your fitness & wellness experience?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "financial_services",
        "name": "Financial Services",
        "questions": [
            {"name": "Advice clarity", "body": "💡 How clear and understandable was the advice given?", "options": ["Unclear", "Clear", "Very clear"]},
            {"name": "Product suitability", "body": "📋 Was the recommended product suitable for your needs?", "options": ["No", "Yes", "Yes, perfectly matched"]},
            {"name": "Adviser professionalism", "body": "👔 How professional was your adviser?", "options": ["Unprofessional", "Professional", "Highly professional"]},
            {"name": "Response time", "body": "⏱️ How quickly did we respond to your queries?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Value for money", "body": "💰 Do you feel fees or charges were fair?", "options": ["Poor value", "Fair", "Excellent value"]},
            {"name": "Onboarding experience", "body": "📝 How smooth was the onboarding or application process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Would recommend", "body": "📢 Would you recommend our services to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Communication quality", "body": "💬 How would you rate ongoing communication from us?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Trust & confidence", "body": "🔒 Do you feel confident and trusting in our advice?", "options": ["No", "Somewhat", "Yes, completely"]},
            {"name": "Compliance & transparency", "body": "📄 Were all terms, risks, and costs explained transparently?", "options": ["No", "Mostly", "Yes, fully"]},
            {"name": "Digital platform rating", "body": "💻 How would you rate our online banking or portal?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Application process", "body": "📑 How easy was completing the application?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Mortgage/loan handling", "body": "🏠 (If applicable) How satisfied were you with mortgage or loan handling?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Claims experience", "body": "🛡️ (If applicable) How was your claims experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Renewal process", "body": "🔄 How smooth was the renewal process?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Documentation clarity", "body": "📄 Were all documents clear and easy to understand?", "options": ["No", "Mostly", "Yes, very clear"]},
            {"name": "Fee transparency", "body": "💰 Were all fees disclosed upfront?", "options": ["No", "Mostly", "Yes, fully"]},
            {"name": "Switch/transfer experience", "body": "🔄 How smooth was switching or transferring to us?", "options": ["Difficult", "Smooth", "Very smooth"]},
            {"name": "Complaint handling", "body": "🎧 (If applicable) How well was your complaint handled?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Overall service rating", "body": "🌟 Overall, how would you rate our financial service?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "logistics_delivery",
        "name": "Logistics & Delivery",
        "questions": [
            {"name": "Delivery speed", "body": "⚡ How would you rate the speed of delivery?", "options": ["Too slow", "Acceptable", "Very fast"]},
            {"name": "Packaging condition", "body": "📦 Did your parcel arrive in good condition?", "options": ["Damaged", "Good", "Perfect condition"]},
            {"name": "Driver attitude", "body": "🚛 How friendly and professional was the driver?", "options": ["Unfriendly", "Polite", "Very friendly & helpful"]},
            {"name": "Delivery accuracy", "body": "✅ Was your delivery made to the correct address and safe place?", "options": ["No", "Yes", "Yes, with care"]},
            {"name": "Communication/tracking", "body": "📍 How accurate and useful was the tracking information?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Would recommend", "body": "📢 Would you recommend our delivery service to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Collection experience", "body": "🏢 (If applicable) How was your collection experience from depot?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Returns process", "body": "🔄 How easy was the returns process (if used)?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Value for money", "body": "💰 Do you feel delivery pricing was fair?", "options": ["Too high", "Fair", "Very good value"]},
            {"name": "Repeat use intent", "body": "🔄 Would you use us again for deliveries?", "options": ["Unlikely", "Likely", "Definitely yes"]},
            {"name": "Safe place delivery rating", "body": "🏠 (If applicable) How satisfied were you with safe place instructions followed?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Missed delivery handling", "body": "📝 How well was a missed delivery handled?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Customer service quality", "body": "🎧 How would you rate our customer service team?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "App/portal experience", "body": "📱 How would you rate our app or tracking portal?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Proof of delivery satisfaction", "body": "📸 Was proof of delivery clear and timely?", "options": ["No", "Yes", "Yes, with photo & time"]},
            {"name": "Fragile item handling", "body": "⚠️ Were fragile items handled with care?", "options": ["No", "Yes", "Yes, clearly well protected"]},
            {"name": "Same-day service rating", "body": "⏱️ (If applicable) How satisfied were you with same-day delivery?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "International delivery rating", "body": "🌍 (If applicable) How was your international delivery experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Business account experience", "body": "🏢 (If applicable) How satisfied are you with our business account service?", "options": ["Unsatisfied", "Satisfied", "Very satisfied"]},
            {"name": "Overall delivery rating", "body": "🚚 Overall, how would you rate our delivery service?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "events_entertainment",
        "name": "Events & Entertainment",
        "questions": [
            {"name": "Event organisation", "body": "🎪 How well organised was the event overall?", "options": ["Poorly", "Well", "Very well organised"]},
            {"name": "Venue quality", "body": "🏟️ How would you rate the venue?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Staff friendliness", "body": "😊 How friendly and helpful were event staff?", "options": ["Unfriendly", "Friendly", "Very warm & helpful"]},
            {"name": "Value for money", "body": "💰 Did the event feel worth the ticket price?", "options": ["Poor value", "Fair value", "Excellent value"]},
            {"name": "Would recommend", "body": "📢 Would you recommend this event to others?", "options": ["No", "Maybe", "Yes, definitely"]},
            {"name": "Return intent", "body": "🔄 Would you attend another event organised by us?", "options": ["Unlikely", "Likely", "Definitely yes"]},
            {"name": "Ticketing/booking experience", "body": "🎟️ How easy was it to book tickets?", "options": ["Difficult", "Easy", "Very easy"]},
            {"name": "Queue management", "body": "🚶 How well were queues managed at entry or bars?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Food & drink quality", "body": "🍔 How would you rate the food and drink options?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Parking & transport", "body": "🅿️ How convenient was parking or public transport access?", "options": ["Difficult", "Fine", "Very easy"]},
            {"name": "Safety & security feel", "body": "🛡️ Did you feel safe and secure throughout?", "options": ["No", "Yes", "Yes, very well managed"]},
            {"name": "Speaker/performer rating", "body": "🎤 How would you rate the speaker, performer, or act?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Sound & AV quality", "body": "🔊 How clear and professional was the sound and AV?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Networking opportunity", "body": "🤝 How valuable were the networking opportunities (if applicable)?", "options": ["Not valuable", "Valuable", "Very valuable"]},
            {"name": "Programme/schedule quality", "body": "📅 Was the event schedule well paced and interesting?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Signage & navigation", "body": "🧭 Was it easy to find your way around the venue?", "options": ["No", "Yes", "Yes, very clear"]},
            {"name": "Accessibility provision", "body": "♿ How well did the event accommodate accessibility needs?", "options": ["Poorly", "Well", "Very well"]},
            {"name": "Merchandise experience", "body": "🛍️ (If applicable) How was the merchandise buying experience?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Post-event communication", "body": "📧 How useful was any follow-up or post-event communication?", "options": ["Not useful", "Useful", "Very useful"]},
            {"name": "Overall event rating", "body": "🎉 Overall, how would you rate this event?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
    {
        "slug": "employee_survey",
        "name": "Employee Survey",
        "questions": [
            {"name": "Morale", "body": "📈 How would you describe the current mood and spirit within our team?", "options": ["Low", "Moderate", "High"]},
            {"name": "Work-life balance", "body": "⚖️ How well are you able to separate work from personal time?", "options": ["Poorly", "Adequately", "Very well"]},
            {"name": "Feeling valued", "body": "💙 Do you feel that your contributions are genuinely appreciated here?", "options": ["No", "Somewhat", "Yes, absolutely"]},
            {"name": "Workload", "body": "📊 How do you find your current volume of work?", "options": ["Overwhelming", "Manageable", "Too light"]},
            {"name": "Motivation", "body": "🔥 How energized and driven do you feel to perform well in your role?", "options": ["Not motivated", "Moderately motivated", "Highly motivated"]},
            {"name": "Manager communication", "body": "🗣️ Does your manager share information, feedback, and expectations clearly?", "options": ["Rarely", "Sometimes", "Consistently"]},
            {"name": "Manager fairness", "body": "⚖️ Do you feel your manager treats all team members fairly and without favoritism?", "options": ["No", "Sometimes", "Yes, always"]},
            {"name": "Recognition", "body": "🏆 How often do you receive meaningful recognition for your efforts?", "options": ["Rarely or never", "Sometimes", "Regularly"]},
            {"name": "Team collaboration", "body": "🤝 How smoothly does your team share information and support one another?", "options": ["Poorly", "Well", "Excellently"]},
            {"name": "Inclusion & belonging", "body": "🌈 Do you feel safe and welcome to be your authentic self at work?", "options": ["No", "Sometimes", "Yes, fully"]},
            {"name": "Career progression", "body": "📈 Are you satisfied with the opportunities to grow and advance here?", "options": ["No", "Neutral", "Yes"]},
            {"name": "Training quality", "body": "📚 How useful and relevant is the training you receive for your job?", "options": ["Not useful", "Somewhat useful", "Very useful"]},
            {"name": "Goal clarity", "body": "🎯 Do you clearly understand your most important work goals right now?", "options": ["No", "Partially", "Yes, clearly"]},
            {"name": "Role clarity", "body": "📄 Do you have a clear understanding of your daily responsibilities and expectations?", "options": ["No", "Partly", "Yes, very clear"]},
            {"name": "Job satisfaction", "body": "😊 Overall, how content are you with your current role and daily work?", "options": ["Dissatisfied", "Neutral", "Satisfied"]},
            {"name": "Internal communication", "body": "📢 How effective is the flow of company news and important updates?", "options": ["Poor", "Good", "Excellent"]},
            {"name": "Pay & benefits fairness", "body": "💰 Do you believe your total compensation is fair compared to your role and effort?", "options": ["No", "Neutral", "Yes"]},
            {"name": "Remote/hybrid flexibility", "body": "🏡 Does your current work arrangement give you the flexibility you need?", "options": ["No", "Partially", "Yes, fully"]},
            {"name": "Psychological safety", "body": "🛡️ Can you speak up with concerns or new ideas without fear of negative consequences?", "options": ["No", "Sometimes", "Yes, confidently"]},
            {"name": "Overall employee experience", "body": "🌟 How would you rate this company as a place to work, all things considered?", "options": ["Poor", "Good", "Excellent"]},
        ],
    },
]
