import React, { useEffect, useMemo, useState } from 'react'
import { BookOpen, ChevronRight, HelpCircle, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { Button } from './Button'
import { Modal } from '@/components/ui/Modal'
import { sanitizeCmsHtml } from '../../lib/sanitizeHtml'
import RichEditor from './RichEditor'

const blankCategory = { name: '', description: '', slug: '', sort_order: 0 }
const blankItem = { title: '', body: '', category_id: '', state: 'draft', sort_order: 0, linked_service: '', linked_provider: '' }
const SERVICE_OPTIONS = [
  { value: '', label: '— none —' },
  { value: 'interview', label: 'Interview / Recruitment' },
  { value: 'survey', label: 'WhatsApp Surveys' },
  { value: 'customer_feedback', label: 'Customer Feedback' },
  { value: 'expo', label: 'Expo' },
  { value: 'smart_card', label: 'Smart Card' },
  { value: 'campaigns', label: 'Campaigns' },
  { value: 'shared', label: 'Account / Billing / Support' },
]
export default function KnowledgeBase({ title, kind = 'article', load, saveCategory, saveItem, deleteCategory, deleteItem }) {
  const [data, setData] = useState({ categories: [], items: [] })
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState(null)
  const [categoryForm, setCategoryForm] = useState(null)
  const [itemForm, setItemForm] = useState(null)
  const [reading, setReading] = useState(null)
  const [error, setError] = useState('')
  const refresh = async () => { try { setError(''); setData(await load()) } catch (e) { setError(e.message || 'Could not load content') } }
  useEffect(() => { refresh() }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const noun = kind === 'faq' ? 'question' : 'article'
  const items = useMemo(() => data.items.filter((x) => (!category || String(x.category_id) === String(category.id)) && (!query || `${x.title || x.question} ${x.body || x.answer}`.toLowerCase().includes(query.toLowerCase()))), [data.items, category, query])
  const editItem = (x) => setItemForm({ id: x.id, title: x.title || x.question || '', body: x.body || x.answer || '', category_id: x.category_id || '', state: x.state || (x.is_published ? 'published' : 'draft'), sort_order: x.sort_order || 0, linked_service: x.linked_service || '', linked_provider: x.linked_provider || '' })
  return <div className="h-full overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-4">
    {error ? <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div> : null}
    <div className="flex items-center gap-3"><div><h2 className="text-lg font-bold">{category ? category.name : `${title} categories`}</h2><p className="text-xs text-muted-foreground">{data.categories.length} categories · {data.items.length} {noun}s</p></div><div className="ml-auto flex gap-2"><Button variant="outline" size="sm" onClick={() => setCategoryForm(blankCategory)}><Plus /> New category</Button><Button size="sm" onClick={() => setItemForm({ ...blankItem, category_id: category?.id || data.categories[0]?.id || '' })}><Plus /> New {noun}</Button></div></div>
    <label className="relative block"><Search className="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={`Search categories and ${noun}s…`} className="h-9 w-full rounded-md border border-input bg-surface pl-8 pr-3 text-sm outline-none" /></label>
    {!category && !query ? <ul className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.categories.map((c) => { const rows = data.items.filter((x) => String(x.category_id) === String(c.id)); return <li key={c.id} className="rounded-xl border border-border bg-surface p-4 shadow-panel"><div className="flex gap-2"><span className="grid size-9 place-items-center rounded-lg bg-accent text-accent-foreground">{kind === 'faq' ? <HelpCircle /> : <BookOpen />}</span><button className="min-w-0 flex-1 text-left" onClick={() => setCategory(c)}><strong className="block truncate text-sm">{c.name}</strong><span className="line-clamp-2 text-xs text-muted-foreground">{c.description || c.slug || 'No description'}</span></button><Button variant="ghost" size="icon" className="size-7" onClick={() => setCategoryForm(c)}><Pencil /></Button><Button variant="ghost" size="icon" className="size-7 text-destructive" onClick={async () => { if (window.confirm(`Delete ${c.name}?`)) { await deleteCategory(c.id); refresh() } }}><Trash2 /></Button></div><div className="mt-3 border-t pt-3 text-xs text-muted-foreground">{rows.length} items · {rows.filter((x) => x.state === 'published' || x.is_published).length} live</div><Button variant="ghost" size="sm" className="mt-2 w-full justify-between" onClick={() => setCategory(c)}>Open category <ChevronRight /></Button></li> })}</ul> : null}
    {category || query ? <div className="overflow-hidden rounded-xl border border-border bg-surface shadow-panel"><div className="flex items-center border-b p-3"><strong className="text-sm">{category?.name || 'Search results'}</strong>{category ? <Button variant="ghost" size="sm" className="ml-auto" onClick={() => setCategory(null)}>All categories</Button> : null}</div><ul className="divide-y divide-border">{items.map((x) => <li key={x.id} className="flex items-center gap-3 p-3 hover:bg-surface-subtle"><button className="min-w-0 flex-1 text-left" onClick={() => setReading(x)}><strong className="block truncate text-sm">{x.title || x.question}</strong><span className="text-xs text-muted-foreground">{x.state || (x.is_published ? 'published' : 'draft')} · {x.linked_service ? `service:${x.linked_service} · ` : ''}{x.usage_count != null ? `${x.usage_count} Ask AI · ` : ''}{x.helpful_count != null ? `${x.helpful_count}↑/${x.unhelpful_count || 0}↓ · ` : ''}{x.views || 0} views</span></button><Button variant="outline" size="sm" onClick={() => editItem(x)}><Pencil /> Edit</Button><Button variant="ghost" size="icon" className="text-destructive" onClick={async () => { if (window.confirm(`Delete this ${noun}?`)) { await deleteItem(x.id); refresh() } }}><Trash2 /></Button></li>)}{!items.length ? <li className="p-8 text-center text-sm text-muted-foreground">Nothing here yet.</li> : null}</ul></div> : null}
    <Modal open={!!reading} onOpenChange={(o) => !o && setReading(null)} title={reading?.title || reading?.question} className="support-disk support-disk-dialog max-h-[85vh] max-w-3xl overflow-y-auto"><div className="kb-prose text-sm" dangerouslySetInnerHTML={{ __html: sanitizeCmsHtml(reading?.body || reading?.answer || '') }} /></Modal>
    <Modal open={!!categoryForm} onOpenChange={(o) => !o && setCategoryForm(null)} className="support-disk support-disk-dialog max-w-lg" title={categoryForm?.id ? 'Edit category' : 'New category'} footer={<><Button variant="ghost" onClick={() => setCategoryForm(null)}>Cancel</Button><Button onClick={async () => { await saveCategory(categoryForm); setCategoryForm(null); refresh() }}>Save</Button></>}><div className="space-y-3"><input value={categoryForm?.name || ''} onChange={(e) => setCategoryForm({ ...categoryForm, name: e.target.value })} placeholder="Category name" className="h-9 w-full rounded-md border px-3" /><textarea value={categoryForm?.description || ''} onChange={(e) => setCategoryForm({ ...categoryForm, description: e.target.value })} placeholder="Description" className="min-h-24 w-full rounded-md border p-3" /></div></Modal>
    <Modal open={!!itemForm} onOpenChange={(o) => !o && setItemForm(null)} title={`${itemForm?.id ? 'Edit' : 'New'} ${noun}`} className="support-disk support-disk-dialog max-h-[90vh] max-w-3xl overflow-y-auto" footer={<><Button variant="ghost" onClick={() => setItemForm(null)}>Cancel</Button><Button onClick={async () => { await saveItem(itemForm); setItemForm(null); refresh() }}>Save</Button></>}><div className="space-y-3"><select value={itemForm?.category_id || ''} onChange={(e) => setItemForm({ ...itemForm, category_id: e.target.value })} className="h-9 w-full rounded-md border px-3">{data.categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input value={itemForm?.title || ''} onChange={(e) => setItemForm({ ...itemForm, title: e.target.value })} placeholder={kind === 'faq' ? 'Question' : 'Article title'} className="h-9 w-full rounded-md border px-3" />{kind === 'faq' ? <><label className="block text-xs text-muted-foreground">Linked service / product (visibility)</label><select value={itemForm?.linked_service || ''} onChange={(e) => setItemForm({ ...itemForm, linked_service: e.target.value })} className="h-9 w-full rounded-md border px-3">{SERVICE_OPTIONS.map((o) => <option key={o.value || 'none'} value={o.value}>{o.label}</option>)}</select><label className="block text-xs text-muted-foreground">Linked integration provider (release gate)</label><input value={itemForm?.linked_provider || ''} onChange={(e) => setItemForm({ ...itemForm, linked_provider: e.target.value })} placeholder="e.g. zoho_recruit (optional)" className="h-9 w-full rounded-md border px-3" /></> : null}<RichEditor value={itemForm?.body || ''} onChange={(body) => setItemForm({ ...itemForm, body })} /></div></Modal>
  </div></div>
}
