import React, { useMemo, useRef, useState } from 'react'
import { Archive, ArrowLeft, Bold, Check, Italic, Link2, List, Lock, MoreHorizontal, Paperclip, Plus, Search, Send, Sparkles, Zap } from 'lucide-react'
import { Button } from './Button'
import { Textarea } from './ui/textarea'
import { Tabs, TabsList, TabsTrigger } from './ui/tabs'
import { Popover, PopoverContent, PopoverTrigger } from './ui/popover'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from './ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from './ui/dropdown-menu'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from './ui/alert-dialog'
import { InitialsAvatar, STATUS_META, StatusPill, TagChip } from './bits'
import { cn, dateLabel } from './utils'

export default function TicketDetail({ ticket, messages = [], admins = [], cannedReplies = [], helpLinks = [], faqs = [], onBack, onStatusChange, onAssign, onSend, onPolish, onWriteAi, onArchive }) {
  const [mode, setMode] = useState('reply')
  const [draft, setDraft] = useState('')
  const [cannedQuery, setCannedQuery] = useState('')
  const [linkQuery, setLinkQuery] = useState('')
  const [aiOpen, setAiOpen] = useState(false)
  const [confirmArchive, setConfirmArchive] = useState(false)
  const [aiSuggestion, setAiSuggestion] = useState('')
  const [tags, setTags] = useState(ticket.category ? [ticket.category] : ['support'])
  const [busy, setBusy] = useState(false)
  const textareaRef = useRef(null)
  const requester = ticket.requester_email || ticket.created_by_email || 'Customer'
  const filteredCanned = useMemo(() => cannedReplies.filter((c) => `${c.title} ${c.answer || c.body}`.toLowerCase().includes(cannedQuery.toLowerCase())), [cannedReplies, cannedQuery])
  const articles = useMemo(() => [...helpLinks.map((x) => ({ id: `h${x.id}`, title: x.title || x.label, body: `[${x.title || x.label}](${x.url})` })), ...faqs.map((x) => ({ id: `f${x.id}`, title: x.question, body: x.answer }))].filter((a) => `${a.title} ${a.body}`.toLowerCase().includes(linkQuery.toLowerCase())), [helpLinks, faqs, linkQuery])
  const insert = (snippet) => { setDraft((d) => d ? `${d.trimEnd()}\n\n${snippet}` : snippet); requestAnimationFrame(() => textareaRef.current?.focus()) }
  const wrap = (token) => { const el = textareaRef.current; if (!el) return; const { selectionStart: s, selectionEnd: e } = el; const selected = draft.slice(s, e) || 'text'; setDraft(`${draft.slice(0, s)}${token}${selected}${token}${draft.slice(e)}`); requestAnimationFrame(() => el.focus()) }
  const polish = async () => { if (!draft.trim()) return; setBusy(true); try { setAiSuggestion(await onPolish(draft)); setAiOpen(true) } finally { setBusy(false) } }
  const writeAi = async () => { setBusy(true); try { setDraft(await onWriteAi()); requestAnimationFrame(() => textareaRef.current?.focus()) } finally { setBusy(false) } }
  const send = async () => { if (!draft.trim()) return; setBusy(true); try { await onSend(draft.trim(), mode === 'note'); setDraft('') } finally { setBusy(false) } }

  return <section className="flex h-full min-h-0 min-w-0 flex-1 flex-col bg-surface" aria-label="Ticket detail">
    <header className="shrink-0 border-b border-border px-4 py-3">
      <Button variant="ghost" size="sm" className="mb-2 h-8 text-xs" onClick={onBack}><ArrowLeft className="size-4" /> Back to all tickets</Button>
      <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3"><div className="min-w-0"><h2 className="truncate text-base font-bold">{ticket.subject}</h2><p className="mt-0.5 truncate text-xs text-muted-foreground">{ticket.public_ref} · {requester} · via {ticket.channel || 'email'}</p></div>
        <div className="flex shrink-0 items-center gap-1.5">
          <Select value={ticket.status} onValueChange={onStatusChange}><SelectTrigger className="h-8 w-[190px] text-xs"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(STATUS_META).map(([s, m]) => <SelectItem key={s} value={s}>{m.label}</SelectItem>)}</SelectContent></Select>
          <Select value={String(ticket.assigned_admin_user_id || 'unassigned')} onValueChange={(v) => onAssign(v === 'unassigned' ? '' : v)}><SelectTrigger className="h-8 w-[190px] text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="unassigned">Unassigned</SelectItem>{admins.map((a) => <SelectItem key={a.id} value={String(a.id)}>{a.email}</SelectItem>)}</SelectContent></Select>
          <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="size-8"><MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><DropdownMenuLabel className="text-[11px] uppercase">Ticket actions</DropdownMenuLabel><DropdownMenuItem>Mark as spam</DropdownMenuItem><DropdownMenuItem>Export conversation</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onSelect={() => setConfirmArchive(true)}><Archive className="size-4" /> Archive ticket</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
        </div>
      </div>
      <div className="mt-2.5 flex flex-wrap items-center gap-1.5"><StatusPill status={ticket.status} />{tags.map((tag) => <TagChip key={tag} label={tag} />)}<Popover><PopoverTrigger asChild><button className="inline-flex items-center gap-1 rounded-md border border-dashed border-border px-1.5 py-0.5 text-[11px] font-medium text-muted-foreground hover:bg-secondary"><Plus className="size-3" /> Tag</button></PopoverTrigger><PopoverContent align="start" className="w-48 p-1">{['billing', 'technical', 'refund', 'how-to', 'escalation'].filter((tag) => !tags.includes(tag)).map((tag) => <button key={tag} onClick={() => setTags((prev) => [...prev, tag])} className="block w-full rounded-sm px-2 py-1.5 text-left text-sm hover:bg-secondary">{tag}</button>)}</PopoverContent></Popover><span className="ml-auto text-[11px] text-muted-foreground">Assigned to <span className="font-medium text-foreground">{ticket.assigned_admin_email || 'Unassigned'}</span></span></div>
    </header>
    <div className="min-h-0 flex-1 space-y-4 overflow-y-auto bg-surface-subtle px-4 py-4">{messages.map((m) => <article key={m.id} className={cn('flex gap-2.5', m.sender_type === 'admin' && !m.is_internal_note && 'flex-row-reverse')}><InitialsAvatar name={m.sender_email || m.sender_type} /><div className={cn('max-w-[42rem] min-w-0 rounded-lg border px-3 py-2.5 shadow-panel', m.is_internal_note ? 'border-note/30 bg-note-bg' : m.sender_type === 'admin' ? 'border-transparent bg-accent' : 'border-border bg-surface')}><p className="flex flex-wrap items-center gap-1.5 text-[11px] text-muted-foreground"><span className="font-semibold text-foreground">{m.sender_email || m.sender_type}</span>{m.is_internal_note ? <span className="inline-flex items-center gap-1 rounded-full bg-note/15 px-1.5 py-px font-semibold text-note"><Lock className="size-2.5" /> Internal note</span> : null}<span>{dateLabel(m.created_at)}</span></p><p className="mt-1 text-sm whitespace-pre-wrap">{m.body}</p></div></article>)}</div>
    <footer className="shrink-0 border-t border-border p-3">
      <Tabs value={mode} onValueChange={setMode}><TabsList className="h-8"><TabsTrigger value="reply" className="text-xs">Reply to customer</TabsTrigger><TabsTrigger value="note" className="text-xs"><Lock className="size-3" /> Internal note</TabsTrigger></TabsList></Tabs>
      <div className={cn('mt-2 rounded-lg border', mode === 'note' ? 'border-note/40 bg-note-bg' : 'border-border bg-surface')}>
        <div className="flex flex-wrap items-center gap-0.5 border-b border-border/70 px-1.5 py-1">
          <Button variant="ghost" size="icon" className="size-7" onClick={() => wrap('**')}><Bold className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-7" onClick={() => wrap('_')}><Italic className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-7" onClick={() => insert('- ')}><List className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-7" onClick={() => wrap('[]')}><Link2 className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-7"><Paperclip className="size-3.5" /></Button><span className="mx-1 h-4 w-px bg-border" />
          <Popover><PopoverTrigger asChild><Button variant="ghost" size="sm" className="h-7 px-2 text-xs"><Zap className="size-3.5" /> Canned replies</Button></PopoverTrigger><PopoverContent align="start" className="w-80 p-0"><div className="relative border-b border-border"><Search className="pointer-events-none absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted-foreground" /><input autoFocus value={cannedQuery} onChange={(e) => setCannedQuery(e.target.value)} placeholder="Search templates…" className="h-9 w-full bg-transparent pr-2 pl-8 text-sm outline-none" /></div><div className="max-h-72 overflow-y-auto p-1">{filteredCanned.map((c) => <button key={c.id} onClick={() => insert(c.answer || c.body)} className="block w-full rounded-sm px-2 py-1.5 text-left hover:bg-secondary"><span className="block text-sm font-medium">{c.title}</span><span className="line-clamp-1 block text-xs text-muted-foreground">{c.answer || c.body}</span></button>)}</div></PopoverContent></Popover>
          <Popover><PopoverTrigger asChild><Button variant="ghost" size="sm" className="h-7 px-2 text-xs"><Link2 className="size-3.5" /> Insert help link</Button></PopoverTrigger><PopoverContent align="start" className="w-80 p-0"><div className="relative border-b border-border"><Search className="pointer-events-none absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted-foreground" /><input autoFocus value={linkQuery} onChange={(e) => setLinkQuery(e.target.value)} placeholder="Search help centre & FAQs…" className="h-9 w-full bg-transparent pr-2 pl-8 text-sm outline-none" /></div><div className="max-h-72 overflow-y-auto p-1">{articles.map((a) => <button key={a.id} onClick={() => insert(a.body)} className="block w-full rounded-sm px-2 py-1.5 text-left hover:bg-secondary"><span className="block text-sm font-medium">{a.title}</span><span className="line-clamp-1 block text-xs text-muted-foreground">{a.body}</span></button>)}</div></PopoverContent></Popover>
          <Button variant="ghost" size="sm" className="h-7 px-2 text-xs text-primary" disabled={busy} onClick={writeAi}><Sparkles className="size-3.5" /> Write with AI</Button>
          <Button variant="ghost" size="sm" className="h-7 px-2 text-xs text-primary" disabled={busy} onClick={polish}><Sparkles className="size-3.5" /> Fix my reply with AI</Button>
        </div>
        <Textarea ref={textareaRef} value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') send() }} placeholder={mode === 'note' ? 'Add a note only your team can see…' : `Reply to ${requester}…`} className="min-h-28 resize-none border-0 bg-transparent text-sm shadow-none focus-visible:ring-0" />
        <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border/70 px-2 py-1.5"><p className="text-[11px] text-muted-foreground">{mode === 'note' ? 'Not visible to the customer' : '⌘ + Enter to send'}</p><div className="flex items-center gap-1.5"><Select defaultValue={ticket.status} onValueChange={onStatusChange}><SelectTrigger className="h-8 w-[170px] text-xs"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(STATUS_META).map(([s, m]) => <SelectItem key={s} value={s}>Send &amp; set {m.label}</SelectItem>)}</SelectContent></Select><Button size="sm" className="h-8" onClick={send} disabled={!draft.trim() || busy}><Send className="size-3.5" />{mode === 'note' ? 'Add note' : 'Send reply'}</Button></div></div>
      </div>
    </footer>
    <Dialog open={aiOpen} onOpenChange={setAiOpen}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><Sparkles className="size-4 text-primary" /> AI-polished reply</DialogTitle><DialogDescription>Grammar, tone and clarity improved. Review the changes before applying.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border border-border bg-surface-subtle p-3"><p className="mb-1.5 text-[11px] font-semibold tracking-wider text-muted-foreground uppercase">Before</p><p className="text-sm whitespace-pre-wrap">{draft}</p></div><div className="rounded-lg border border-primary/30 bg-accent p-3"><p className="mb-1.5 text-[11px] font-semibold tracking-wider text-accent-foreground uppercase">After</p><p className="text-sm whitespace-pre-wrap">{aiSuggestion}</p></div></div><DialogFooter><Button variant="ghost" onClick={() => setAiOpen(false)}>Keep original</Button><Button onClick={() => { setDraft(aiSuggestion); setAiOpen(false) }}><Check className="size-4" /> Use this version</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={confirmArchive} onOpenChange={setConfirmArchive}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Archive ticket {ticket.public_ref}?</AlertDialogTitle><AlertDialogDescription>The ticket will be closed and moved to the Archive. Nothing is permanently deleted.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={onArchive}>Archive</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>
}
