/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as BookTokenRouteImport } from './routes/book.$token'
import { Route as AppSurveysRouteImport } from './routes/_app.surveys'
import { Route as AppRecoveryRouteImport } from './routes/_app.recovery'
import { Route as AppPackagesRouteImport } from './routes/_app.packages'
import { Route as AppInterviewsRouteImport } from './routes/_app.interviews'
import { Route as AppFollowUpRouteImport } from './routes/_app.follow-up'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppSurveysIndexRouteImport } from './routes/_app.surveys.index'
import { Route as AppRecoveryIndexRouteImport } from './routes/_app.recovery.index'
import { Route as AppInterviewsIndexRouteImport } from './routes/_app.interviews.index'
import { Route as AppFeedbackIndexRouteImport } from './routes/_app.feedback.index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/_app.appointments.index'
import { Route as AppSurveysResultsRouteImport } from './routes/_app.surveys.results'
import { Route as AppSurveysReportsRouteImport } from './routes/_app.surveys.reports'
import { Route as AppSurveysNewRouteImport } from './routes/_app.surveys.new'
import { Route as AppSurveysIdRouteImport } from './routes/_app.surveys.$id'
import { Route as AppSettingsTeamRouteImport } from './routes/_app.settings.team'
import { Route as AppSettingsSystemRouteImport } from './routes/_app.settings.system'
import { Route as AppSettingsServicesRouteImport } from './routes/_app.settings.services'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppSettingsOptOutRouteImport } from './routes/_app.settings.opt-out'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app.settings.integrations'
import { Route as AppSettingsAuditRouteImport } from './routes/_app.settings.audit'
import { Route as AppRecoveryRecallRouteImport } from './routes/_app.recovery.recall'
import { Route as AppRecoveryOffersRouteImport } from './routes/_app.recovery.offers'
import { Route as AppRecoveryNoShowRouteImport } from './routes/_app.recovery.no-show'
import { Route as AppRecoveryEmergencyRouteImport } from './routes/_app.recovery.emergency'
import { Route as AppInterviewsResultsRouteImport } from './routes/_app.interviews.results'
import { Route as AppInterviewsReportsRouteImport } from './routes/_app.interviews.reports'
import { Route as AppInterviewsNewRouteImport } from './routes/_app.interviews.new'
import { Route as AppInterviewsOrderIdRouteImport } from './routes/_app.interviews.$orderId'
import { Route as AppFeedbackResultsRouteImport } from './routes/_app.feedback.results'
import { Route as AppFeedbackNewRouteImport } from './routes/_app.feedback.new'
import { Route as AppFeedbackCompareRouteImport } from './routes/_app.feedback.compare'
import { Route as AppCampaignsSendRouteImport } from './routes/_app.campaigns.send'
import { Route as AppCampaignsNewRouteImport } from './routes/_app.campaigns.new'
import { Route as AppAppointmentsSetupRouteImport } from './routes/_app.appointments.setup'
import { Route as AppAppointmentsReportsRouteImport } from './routes/_app.appointments.reports'
import { Route as AppAccountUsageRouteImport } from './routes/_app.account.usage'
import { Route as AppAccountSupportRouteImport } from './routes/_app.account.support'
import { Route as AppAccountPackagesRouteImport } from './routes/_app.account.packages'
import { Route as AppAccountBillingRouteImport } from './routes/_app.account.billing'
import { Route as AppInterviewsResultsIndexRouteImport } from './routes/_app.interviews.results.index'
import { Route as AppAccountSupportIndexRouteImport } from './routes/_app.account.support.index'
import { Route as AppInterviewsResultsOrderIdRouteImport } from './routes/_app.interviews.results.$orderId'
import { Route as AppFeedbackLocationIdEditRouteImport } from './routes/_app.feedback.$locationId.edit'
import { Route as AppAccountSupportTicketsRouteImport } from './routes/_app.account.support.tickets'
import { Route as AppAccountSupportFaqRouteImport } from './routes/_app.account.support.faq'
import { Route as AppAccountFeedbackPackagesRouteImport } from './routes/_app.account.feedback.packages'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const BookTokenRoute = BookTokenRouteImport.update({
  id: '/book/$token',
  path: '/book/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSurveysRoute = AppSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoveryRoute = AppRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpRoute = AppFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIndexRoute = AppSurveysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppRecoveryIndexRoute = AppRecoveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppFeedbackIndexRoute = AppFeedbackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFeedbackRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppointmentsRoute,
} as any)
const AppSurveysResultsRoute = AppSurveysResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppSurveysReportsRoute = AppSurveysReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppSurveysNewRoute = AppSurveysNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppSurveysIdRoute = AppSurveysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSystemRoute = AppSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsServicesRoute = AppSettingsServicesRouteImport.update({
  id: '/settings/services',
  path: '/settings/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOptOutRoute = AppSettingsOptOutRouteImport.update({
  id: '/settings/opt-out',
  path: '/settings/opt-out',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoveryRecallRoute = AppRecoveryRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppRecoveryOffersRoute = AppRecoveryOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppRecoveryNoShowRoute = AppRecoveryNoShowRouteImport.update({
  id: '/no-show',
  path: '/no-show',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppRecoveryEmergencyRoute = AppRecoveryEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppInterviewsResultsRoute = AppInterviewsResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppInterviewsReportsRoute = AppInterviewsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppInterviewsNewRoute = AppInterviewsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppInterviewsOrderIdRoute = AppInterviewsOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppFeedbackResultsRoute = AppFeedbackResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppFeedbackRoute,
} as any)
const AppFeedbackNewRoute = AppFeedbackNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppFeedbackRoute,
} as any)
const AppFeedbackCompareRoute = AppFeedbackCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppFeedbackRoute,
} as any)
const AppCampaignsSendRoute = AppCampaignsSendRouteImport.update({
  id: '/campaigns/send',
  path: '/campaigns/send',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsSetupRoute = AppAppointmentsSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppAppointmentsRoute,
} as any)
const AppAppointmentsReportsRoute = AppAppointmentsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAppointmentsRoute,
} as any)
const AppAccountUsageRoute = AppAccountUsageRouteImport.update({
  id: '/account/usage',
  path: '/account/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSupportRoute = AppAccountSupportRouteImport.update({
  id: '/account/support',
  path: '/account/support',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountPackagesRoute = AppAccountPackagesRouteImport.update({
  id: '/account/packages',
  path: '/account/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountBillingRoute = AppAccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsResultsIndexRoute =
  AppInterviewsResultsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInterviewsResultsRoute,
  } as any)
const AppAccountSupportIndexRoute = AppAccountSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountSupportRoute,
} as any)
const AppInterviewsResultsOrderIdRoute =
  AppInterviewsResultsOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AppInterviewsResultsRoute,
  } as any)
const AppFeedbackLocationIdEditRoute =
  AppFeedbackLocationIdEditRouteImport.update({
    id: '/$locationId/edit',
    path: '/$locationId/edit',
    getParentRoute: () => AppFeedbackRoute,
  } as any)
const AppAccountSupportTicketsRoute =
  AppAccountSupportTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AppAccountSupportRoute,
  } as any)
const AppAccountSupportFaqRoute = AppAccountSupportFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppAccountSupportRoute,
} as any)
const AppAccountFeedbackPackagesRoute =
  AppAccountFeedbackPackagesRouteImport.update({
    id: '/account/feedback/packages',
    path: '/account/feedback/packages',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AppAppointmentsRouteWithChildren
  '/feedback': typeof AppFeedbackRouteWithChildren
  '/follow-up': typeof AppFollowUpRoute
  '/interviews': typeof AppInterviewsRouteWithChildren
  '/packages': typeof AppPackagesRoute
  '/recovery': typeof AppRecoveryRouteWithChildren
  '/surveys': typeof AppSurveysRouteWithChildren
  '/book/$token': typeof BookTokenRoute
  '/account/billing': typeof AppAccountBillingRoute
  '/account/packages': typeof AppAccountPackagesRoute
  '/account/support': typeof AppAccountSupportRouteWithChildren
  '/account/usage': typeof AppAccountUsageRoute
  '/appointments/reports': typeof AppAppointmentsReportsRoute
  '/appointments/setup': typeof AppAppointmentsSetupRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/campaigns/send': typeof AppCampaignsSendRoute
  '/feedback/compare': typeof AppFeedbackCompareRoute
  '/feedback/new': typeof AppFeedbackNewRoute
  '/feedback/results': typeof AppFeedbackResultsRoute
  '/interviews/$orderId': typeof AppInterviewsOrderIdRoute
  '/interviews/new': typeof AppInterviewsNewRoute
  '/interviews/reports': typeof AppInterviewsReportsRoute
  '/interviews/results': typeof AppInterviewsResultsRouteWithChildren
  '/recovery/emergency': typeof AppRecoveryEmergencyRoute
  '/recovery/no-show': typeof AppRecoveryNoShowRoute
  '/recovery/offers': typeof AppRecoveryOffersRoute
  '/recovery/recall': typeof AppRecoveryRecallRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/opt-out': typeof AppSettingsOptOutRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/services': typeof AppSettingsServicesRoute
  '/settings/system': typeof AppSettingsSystemRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/surveys/$id': typeof AppSurveysIdRoute
  '/surveys/new': typeof AppSurveysNewRoute
  '/surveys/reports': typeof AppSurveysReportsRoute
  '/surveys/results': typeof AppSurveysResultsRoute
  '/appointments/': typeof AppAppointmentsIndexRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/feedback/': typeof AppFeedbackIndexRoute
  '/interviews/': typeof AppInterviewsIndexRoute
  '/recovery/': typeof AppRecoveryIndexRoute
  '/surveys/': typeof AppSurveysIndexRoute
  '/account/feedback/packages': typeof AppAccountFeedbackPackagesRoute
  '/account/support/faq': typeof AppAccountSupportFaqRoute
  '/account/support/tickets': typeof AppAccountSupportTicketsRoute
  '/feedback/$locationId/edit': typeof AppFeedbackLocationIdEditRoute
  '/interviews/results/$orderId': typeof AppInterviewsResultsOrderIdRoute
  '/account/support/': typeof AppAccountSupportIndexRoute
  '/interviews/results/': typeof AppInterviewsResultsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/follow-up': typeof AppFollowUpRoute
  '/packages': typeof AppPackagesRoute
  '/book/$token': typeof BookTokenRoute
  '/': typeof AppIndexRoute
  '/account/billing': typeof AppAccountBillingRoute
  '/account/packages': typeof AppAccountPackagesRoute
  '/account/usage': typeof AppAccountUsageRoute
  '/appointments/reports': typeof AppAppointmentsReportsRoute
  '/appointments/setup': typeof AppAppointmentsSetupRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/campaigns/send': typeof AppCampaignsSendRoute
  '/feedback/compare': typeof AppFeedbackCompareRoute
  '/feedback/new': typeof AppFeedbackNewRoute
  '/feedback/results': typeof AppFeedbackResultsRoute
  '/interviews/$orderId': typeof AppInterviewsOrderIdRoute
  '/interviews/new': typeof AppInterviewsNewRoute
  '/interviews/reports': typeof AppInterviewsReportsRoute
  '/recovery/emergency': typeof AppRecoveryEmergencyRoute
  '/recovery/no-show': typeof AppRecoveryNoShowRoute
  '/recovery/offers': typeof AppRecoveryOffersRoute
  '/recovery/recall': typeof AppRecoveryRecallRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/opt-out': typeof AppSettingsOptOutRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/services': typeof AppSettingsServicesRoute
  '/settings/system': typeof AppSettingsSystemRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/surveys/$id': typeof AppSurveysIdRoute
  '/surveys/new': typeof AppSurveysNewRoute
  '/surveys/reports': typeof AppSurveysReportsRoute
  '/surveys/results': typeof AppSurveysResultsRoute
  '/appointments': typeof AppAppointmentsIndexRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/feedback': typeof AppFeedbackIndexRoute
  '/interviews': typeof AppInterviewsIndexRoute
  '/recovery': typeof AppRecoveryIndexRoute
  '/surveys': typeof AppSurveysIndexRoute
  '/account/feedback/packages': typeof AppAccountFeedbackPackagesRoute
  '/account/support/faq': typeof AppAccountSupportFaqRoute
  '/account/support/tickets': typeof AppAccountSupportTicketsRoute
  '/feedback/$locationId/edit': typeof AppFeedbackLocationIdEditRoute
  '/interviews/results/$orderId': typeof AppInterviewsResultsOrderIdRoute
  '/account/support': typeof AppAccountSupportIndexRoute
  '/interviews/results': typeof AppInterviewsResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/appointments': typeof AppAppointmentsRouteWithChildren
  '/_app/feedback': typeof AppFeedbackRouteWithChildren
  '/_app/follow-up': typeof AppFollowUpRoute
  '/_app/interviews': typeof AppInterviewsRouteWithChildren
  '/_app/packages': typeof AppPackagesRoute
  '/_app/recovery': typeof AppRecoveryRouteWithChildren
  '/_app/surveys': typeof AppSurveysRouteWithChildren
  '/book/$token': typeof BookTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/billing': typeof AppAccountBillingRoute
  '/_app/account/packages': typeof AppAccountPackagesRoute
  '/_app/account/support': typeof AppAccountSupportRouteWithChildren
  '/_app/account/usage': typeof AppAccountUsageRoute
  '/_app/appointments/reports': typeof AppAppointmentsReportsRoute
  '/_app/appointments/setup': typeof AppAppointmentsSetupRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/campaigns/send': typeof AppCampaignsSendRoute
  '/_app/feedback/compare': typeof AppFeedbackCompareRoute
  '/_app/feedback/new': typeof AppFeedbackNewRoute
  '/_app/feedback/results': typeof AppFeedbackResultsRoute
  '/_app/interviews/$orderId': typeof AppInterviewsOrderIdRoute
  '/_app/interviews/new': typeof AppInterviewsNewRoute
  '/_app/interviews/reports': typeof AppInterviewsReportsRoute
  '/_app/interviews/results': typeof AppInterviewsResultsRouteWithChildren
  '/_app/recovery/emergency': typeof AppRecoveryEmergencyRoute
  '/_app/recovery/no-show': typeof AppRecoveryNoShowRoute
  '/_app/recovery/offers': typeof AppRecoveryOffersRoute
  '/_app/recovery/recall': typeof AppRecoveryRecallRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/opt-out': typeof AppSettingsOptOutRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/services': typeof AppSettingsServicesRoute
  '/_app/settings/system': typeof AppSettingsSystemRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/surveys/$id': typeof AppSurveysIdRoute
  '/_app/surveys/new': typeof AppSurveysNewRoute
  '/_app/surveys/reports': typeof AppSurveysReportsRoute
  '/_app/surveys/results': typeof AppSurveysResultsRoute
  '/_app/appointments/': typeof AppAppointmentsIndexRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/feedback/': typeof AppFeedbackIndexRoute
  '/_app/interviews/': typeof AppInterviewsIndexRoute
  '/_app/recovery/': typeof AppRecoveryIndexRoute
  '/_app/surveys/': typeof AppSurveysIndexRoute
  '/_app/account/feedback/packages': typeof AppAccountFeedbackPackagesRoute
  '/_app/account/support/faq': typeof AppAccountSupportFaqRoute
  '/_app/account/support/tickets': typeof AppAccountSupportTicketsRoute
  '/_app/feedback/$locationId/edit': typeof AppFeedbackLocationIdEditRoute
  '/_app/interviews/results/$orderId': typeof AppInterviewsResultsOrderIdRoute
  '/_app/account/support/': typeof AppAccountSupportIndexRoute
  '/_app/interviews/results/': typeof AppInterviewsResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/appointments'
    | '/feedback'
    | '/follow-up'
    | '/interviews'
    | '/packages'
    | '/recovery'
    | '/surveys'
    | '/book/$token'
    | '/account/billing'
    | '/account/packages'
    | '/account/support'
    | '/account/usage'
    | '/appointments/reports'
    | '/appointments/setup'
    | '/campaigns/new'
    | '/campaigns/send'
    | '/feedback/compare'
    | '/feedback/new'
    | '/feedback/results'
    | '/interviews/$orderId'
    | '/interviews/new'
    | '/interviews/reports'
    | '/interviews/results'
    | '/recovery/emergency'
    | '/recovery/no-show'
    | '/recovery/offers'
    | '/recovery/recall'
    | '/settings/audit'
    | '/settings/integrations'
    | '/settings/opt-out'
    | '/settings/profile'
    | '/settings/services'
    | '/settings/system'
    | '/settings/team'
    | '/surveys/$id'
    | '/surveys/new'
    | '/surveys/reports'
    | '/surveys/results'
    | '/appointments/'
    | '/campaigns/'
    | '/feedback/'
    | '/interviews/'
    | '/recovery/'
    | '/surveys/'
    | '/account/feedback/packages'
    | '/account/support/faq'
    | '/account/support/tickets'
    | '/feedback/$locationId/edit'
    | '/interviews/results/$orderId'
    | '/account/support/'
    | '/interviews/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/follow-up'
    | '/packages'
    | '/book/$token'
    | '/'
    | '/account/billing'
    | '/account/packages'
    | '/account/usage'
    | '/appointments/reports'
    | '/appointments/setup'
    | '/campaigns/new'
    | '/campaigns/send'
    | '/feedback/compare'
    | '/feedback/new'
    | '/feedback/results'
    | '/interviews/$orderId'
    | '/interviews/new'
    | '/interviews/reports'
    | '/recovery/emergency'
    | '/recovery/no-show'
    | '/recovery/offers'
    | '/recovery/recall'
    | '/settings/audit'
    | '/settings/integrations'
    | '/settings/opt-out'
    | '/settings/profile'
    | '/settings/services'
    | '/settings/system'
    | '/settings/team'
    | '/surveys/$id'
    | '/surveys/new'
    | '/surveys/reports'
    | '/surveys/results'
    | '/appointments'
    | '/campaigns'
    | '/feedback'
    | '/interviews'
    | '/recovery'
    | '/surveys'
    | '/account/feedback/packages'
    | '/account/support/faq'
    | '/account/support/tickets'
    | '/feedback/$locationId/edit'
    | '/interviews/results/$orderId'
    | '/account/support'
    | '/interviews/results'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/appointments'
    | '/_app/feedback'
    | '/_app/follow-up'
    | '/_app/interviews'
    | '/_app/packages'
    | '/_app/recovery'
    | '/_app/surveys'
    | '/book/$token'
    | '/_app/'
    | '/_app/account/billing'
    | '/_app/account/packages'
    | '/_app/account/support'
    | '/_app/account/usage'
    | '/_app/appointments/reports'
    | '/_app/appointments/setup'
    | '/_app/campaigns/new'
    | '/_app/campaigns/send'
    | '/_app/feedback/compare'
    | '/_app/feedback/new'
    | '/_app/feedback/results'
    | '/_app/interviews/$orderId'
    | '/_app/interviews/new'
    | '/_app/interviews/reports'
    | '/_app/interviews/results'
    | '/_app/recovery/emergency'
    | '/_app/recovery/no-show'
    | '/_app/recovery/offers'
    | '/_app/recovery/recall'
    | '/_app/settings/audit'
    | '/_app/settings/integrations'
    | '/_app/settings/opt-out'
    | '/_app/settings/profile'
    | '/_app/settings/services'
    | '/_app/settings/system'
    | '/_app/settings/team'
    | '/_app/surveys/$id'
    | '/_app/surveys/new'
    | '/_app/surveys/reports'
    | '/_app/surveys/results'
    | '/_app/appointments/'
    | '/_app/campaigns/'
    | '/_app/feedback/'
    | '/_app/interviews/'
    | '/_app/recovery/'
    | '/_app/surveys/'
    | '/_app/account/feedback/packages'
    | '/_app/account/support/faq'
    | '/_app/account/support/tickets'
    | '/_app/feedback/$locationId/edit'
    | '/_app/interviews/results/$orderId'
    | '/_app/account/support/'
    | '/_app/interviews/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  BookTokenRoute: typeof BookTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$token': {
      id: '/book/$token'
      path: '/book/$token'
      fullPath: '/book/$token'
      preLoaderRoute: typeof BookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/surveys': {
      id: '/_app/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof AppSurveysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recovery': {
      id: '/_app/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof AppRecoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages': {
      id: '/_app/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-up': {
      id: '/_app/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof AppFollowUpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/': {
      id: '/_app/surveys/'
      path: '/'
      fullPath: '/surveys/'
      preLoaderRoute: typeof AppSurveysIndexRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/recovery/': {
      id: '/_app/recovery/'
      path: '/'
      fullPath: '/recovery/'
      preLoaderRoute: typeof AppRecoveryIndexRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/interviews/': {
      id: '/_app/interviews/'
      path: '/'
      fullPath: '/interviews/'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/feedback/': {
      id: '/_app/feedback/'
      path: '/'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AppFeedbackIndexRouteImport
      parentRoute: typeof AppFeedbackRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/': {
      id: '/_app/appointments/'
      path: '/'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppAppointmentsRoute
    }
    '/_app/surveys/results': {
      id: '/_app/surveys/results'
      path: '/results'
      fullPath: '/surveys/results'
      preLoaderRoute: typeof AppSurveysResultsRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/surveys/reports': {
      id: '/_app/surveys/reports'
      path: '/reports'
      fullPath: '/surveys/reports'
      preLoaderRoute: typeof AppSurveysReportsRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/surveys/new': {
      id: '/_app/surveys/new'
      path: '/new'
      fullPath: '/surveys/new'
      preLoaderRoute: typeof AppSurveysNewRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/surveys/$id': {
      id: '/_app/surveys/$id'
      path: '/$id'
      fullPath: '/surveys/$id'
      preLoaderRoute: typeof AppSurveysIdRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/system': {
      id: '/_app/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AppSettingsSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/services': {
      id: '/_app/settings/services'
      path: '/settings/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof AppSettingsServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/opt-out': {
      id: '/_app/settings/opt-out'
      path: '/settings/opt-out'
      fullPath: '/settings/opt-out'
      preLoaderRoute: typeof AppSettingsOptOutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recovery/recall': {
      id: '/_app/recovery/recall'
      path: '/recall'
      fullPath: '/recovery/recall'
      preLoaderRoute: typeof AppRecoveryRecallRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/recovery/offers': {
      id: '/_app/recovery/offers'
      path: '/offers'
      fullPath: '/recovery/offers'
      preLoaderRoute: typeof AppRecoveryOffersRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/recovery/no-show': {
      id: '/_app/recovery/no-show'
      path: '/no-show'
      fullPath: '/recovery/no-show'
      preLoaderRoute: typeof AppRecoveryNoShowRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/recovery/emergency': {
      id: '/_app/recovery/emergency'
      path: '/emergency'
      fullPath: '/recovery/emergency'
      preLoaderRoute: typeof AppRecoveryEmergencyRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/interviews/results': {
      id: '/_app/interviews/results'
      path: '/results'
      fullPath: '/interviews/results'
      preLoaderRoute: typeof AppInterviewsResultsRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/interviews/reports': {
      id: '/_app/interviews/reports'
      path: '/reports'
      fullPath: '/interviews/reports'
      preLoaderRoute: typeof AppInterviewsReportsRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/interviews/new': {
      id: '/_app/interviews/new'
      path: '/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof AppInterviewsNewRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/interviews/$orderId': {
      id: '/_app/interviews/$orderId'
      path: '/$orderId'
      fullPath: '/interviews/$orderId'
      preLoaderRoute: typeof AppInterviewsOrderIdRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/feedback/results': {
      id: '/_app/feedback/results'
      path: '/results'
      fullPath: '/feedback/results'
      preLoaderRoute: typeof AppFeedbackResultsRouteImport
      parentRoute: typeof AppFeedbackRoute
    }
    '/_app/feedback/new': {
      id: '/_app/feedback/new'
      path: '/new'
      fullPath: '/feedback/new'
      preLoaderRoute: typeof AppFeedbackNewRouteImport
      parentRoute: typeof AppFeedbackRoute
    }
    '/_app/feedback/compare': {
      id: '/_app/feedback/compare'
      path: '/compare'
      fullPath: '/feedback/compare'
      preLoaderRoute: typeof AppFeedbackCompareRouteImport
      parentRoute: typeof AppFeedbackRoute
    }
    '/_app/campaigns/send': {
      id: '/_app/campaigns/send'
      path: '/campaigns/send'
      fullPath: '/campaigns/send'
      preLoaderRoute: typeof AppCampaignsSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/setup': {
      id: '/_app/appointments/setup'
      path: '/setup'
      fullPath: '/appointments/setup'
      preLoaderRoute: typeof AppAppointmentsSetupRouteImport
      parentRoute: typeof AppAppointmentsRoute
    }
    '/_app/appointments/reports': {
      id: '/_app/appointments/reports'
      path: '/reports'
      fullPath: '/appointments/reports'
      preLoaderRoute: typeof AppAppointmentsReportsRouteImport
      parentRoute: typeof AppAppointmentsRoute
    }
    '/_app/account/usage': {
      id: '/_app/account/usage'
      path: '/account/usage'
      fullPath: '/account/usage'
      preLoaderRoute: typeof AppAccountUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/support': {
      id: '/_app/account/support'
      path: '/account/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AppAccountSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/packages': {
      id: '/_app/account/packages'
      path: '/account/packages'
      fullPath: '/account/packages'
      preLoaderRoute: typeof AppAccountPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/billing': {
      id: '/_app/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AppAccountBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/results/': {
      id: '/_app/interviews/results/'
      path: '/'
      fullPath: '/interviews/results/'
      preLoaderRoute: typeof AppInterviewsResultsIndexRouteImport
      parentRoute: typeof AppInterviewsResultsRoute
    }
    '/_app/account/support/': {
      id: '/_app/account/support/'
      path: '/'
      fullPath: '/account/support/'
      preLoaderRoute: typeof AppAccountSupportIndexRouteImport
      parentRoute: typeof AppAccountSupportRoute
    }
    '/_app/interviews/results/$orderId': {
      id: '/_app/interviews/results/$orderId'
      path: '/$orderId'
      fullPath: '/interviews/results/$orderId'
      preLoaderRoute: typeof AppInterviewsResultsOrderIdRouteImport
      parentRoute: typeof AppInterviewsResultsRoute
    }
    '/_app/feedback/$locationId/edit': {
      id: '/_app/feedback/$locationId/edit'
      path: '/$locationId/edit'
      fullPath: '/feedback/$locationId/edit'
      preLoaderRoute: typeof AppFeedbackLocationIdEditRouteImport
      parentRoute: typeof AppFeedbackRoute
    }
    '/_app/account/support/tickets': {
      id: '/_app/account/support/tickets'
      path: '/tickets'
      fullPath: '/account/support/tickets'
      preLoaderRoute: typeof AppAccountSupportTicketsRouteImport
      parentRoute: typeof AppAccountSupportRoute
    }
    '/_app/account/support/faq': {
      id: '/_app/account/support/faq'
      path: '/faq'
      fullPath: '/account/support/faq'
      preLoaderRoute: typeof AppAccountSupportFaqRouteImport
      parentRoute: typeof AppAccountSupportRoute
    }
    '/_app/account/feedback/packages': {
      id: '/_app/account/feedback/packages'
      path: '/account/feedback/packages'
      fullPath: '/account/feedback/packages'
      preLoaderRoute: typeof AppAccountFeedbackPackagesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAppointmentsRouteChildren {
  AppAppointmentsReportsRoute: typeof AppAppointmentsReportsRoute
  AppAppointmentsSetupRoute: typeof AppAppointmentsSetupRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
}

const AppAppointmentsRouteChildren: AppAppointmentsRouteChildren = {
  AppAppointmentsReportsRoute: AppAppointmentsReportsRoute,
  AppAppointmentsSetupRoute: AppAppointmentsSetupRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
}

const AppAppointmentsRouteWithChildren = AppAppointmentsRoute._addFileChildren(
  AppAppointmentsRouteChildren,
)

interface AppFeedbackRouteChildren {
  AppFeedbackCompareRoute: typeof AppFeedbackCompareRoute
  AppFeedbackNewRoute: typeof AppFeedbackNewRoute
  AppFeedbackResultsRoute: typeof AppFeedbackResultsRoute
  AppFeedbackIndexRoute: typeof AppFeedbackIndexRoute
  AppFeedbackLocationIdEditRoute: typeof AppFeedbackLocationIdEditRoute
}

const AppFeedbackRouteChildren: AppFeedbackRouteChildren = {
  AppFeedbackCompareRoute: AppFeedbackCompareRoute,
  AppFeedbackNewRoute: AppFeedbackNewRoute,
  AppFeedbackResultsRoute: AppFeedbackResultsRoute,
  AppFeedbackIndexRoute: AppFeedbackIndexRoute,
  AppFeedbackLocationIdEditRoute: AppFeedbackLocationIdEditRoute,
}

const AppFeedbackRouteWithChildren = AppFeedbackRoute._addFileChildren(
  AppFeedbackRouteChildren,
)

interface AppInterviewsResultsRouteChildren {
  AppInterviewsResultsOrderIdRoute: typeof AppInterviewsResultsOrderIdRoute
  AppInterviewsResultsIndexRoute: typeof AppInterviewsResultsIndexRoute
}

const AppInterviewsResultsRouteChildren: AppInterviewsResultsRouteChildren = {
  AppInterviewsResultsOrderIdRoute: AppInterviewsResultsOrderIdRoute,
  AppInterviewsResultsIndexRoute: AppInterviewsResultsIndexRoute,
}

const AppInterviewsResultsRouteWithChildren =
  AppInterviewsResultsRoute._addFileChildren(AppInterviewsResultsRouteChildren)

interface AppInterviewsRouteChildren {
  AppInterviewsOrderIdRoute: typeof AppInterviewsOrderIdRoute
  AppInterviewsNewRoute: typeof AppInterviewsNewRoute
  AppInterviewsReportsRoute: typeof AppInterviewsReportsRoute
  AppInterviewsResultsRoute: typeof AppInterviewsResultsRouteWithChildren
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
}

const AppInterviewsRouteChildren: AppInterviewsRouteChildren = {
  AppInterviewsOrderIdRoute: AppInterviewsOrderIdRoute,
  AppInterviewsNewRoute: AppInterviewsNewRoute,
  AppInterviewsReportsRoute: AppInterviewsReportsRoute,
  AppInterviewsResultsRoute: AppInterviewsResultsRouteWithChildren,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
}

const AppInterviewsRouteWithChildren = AppInterviewsRoute._addFileChildren(
  AppInterviewsRouteChildren,
)

interface AppRecoveryRouteChildren {
  AppRecoveryEmergencyRoute: typeof AppRecoveryEmergencyRoute
  AppRecoveryNoShowRoute: typeof AppRecoveryNoShowRoute
  AppRecoveryOffersRoute: typeof AppRecoveryOffersRoute
  AppRecoveryRecallRoute: typeof AppRecoveryRecallRoute
  AppRecoveryIndexRoute: typeof AppRecoveryIndexRoute
}

const AppRecoveryRouteChildren: AppRecoveryRouteChildren = {
  AppRecoveryEmergencyRoute: AppRecoveryEmergencyRoute,
  AppRecoveryNoShowRoute: AppRecoveryNoShowRoute,
  AppRecoveryOffersRoute: AppRecoveryOffersRoute,
  AppRecoveryRecallRoute: AppRecoveryRecallRoute,
  AppRecoveryIndexRoute: AppRecoveryIndexRoute,
}

const AppRecoveryRouteWithChildren = AppRecoveryRoute._addFileChildren(
  AppRecoveryRouteChildren,
)

interface AppSurveysRouteChildren {
  AppSurveysIdRoute: typeof AppSurveysIdRoute
  AppSurveysNewRoute: typeof AppSurveysNewRoute
  AppSurveysReportsRoute: typeof AppSurveysReportsRoute
  AppSurveysResultsRoute: typeof AppSurveysResultsRoute
  AppSurveysIndexRoute: typeof AppSurveysIndexRoute
}

const AppSurveysRouteChildren: AppSurveysRouteChildren = {
  AppSurveysIdRoute: AppSurveysIdRoute,
  AppSurveysNewRoute: AppSurveysNewRoute,
  AppSurveysReportsRoute: AppSurveysReportsRoute,
  AppSurveysResultsRoute: AppSurveysResultsRoute,
  AppSurveysIndexRoute: AppSurveysIndexRoute,
}

const AppSurveysRouteWithChildren = AppSurveysRoute._addFileChildren(
  AppSurveysRouteChildren,
)

interface AppAccountSupportRouteChildren {
  AppAccountSupportFaqRoute: typeof AppAccountSupportFaqRoute
  AppAccountSupportTicketsRoute: typeof AppAccountSupportTicketsRoute
  AppAccountSupportIndexRoute: typeof AppAccountSupportIndexRoute
}

const AppAccountSupportRouteChildren: AppAccountSupportRouteChildren = {
  AppAccountSupportFaqRoute: AppAccountSupportFaqRoute,
  AppAccountSupportTicketsRoute: AppAccountSupportTicketsRoute,
  AppAccountSupportIndexRoute: AppAccountSupportIndexRoute,
}

const AppAccountSupportRouteWithChildren =
  AppAccountSupportRoute._addFileChildren(AppAccountSupportRouteChildren)

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRouteWithChildren
  AppFeedbackRoute: typeof AppFeedbackRouteWithChildren
  AppFollowUpRoute: typeof AppFollowUpRoute
  AppInterviewsRoute: typeof AppInterviewsRouteWithChildren
  AppPackagesRoute: typeof AppPackagesRoute
  AppRecoveryRoute: typeof AppRecoveryRouteWithChildren
  AppSurveysRoute: typeof AppSurveysRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAccountBillingRoute: typeof AppAccountBillingRoute
  AppAccountPackagesRoute: typeof AppAccountPackagesRoute
  AppAccountSupportRoute: typeof AppAccountSupportRouteWithChildren
  AppAccountUsageRoute: typeof AppAccountUsageRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppCampaignsSendRoute: typeof AppCampaignsSendRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsOptOutRoute: typeof AppSettingsOptOutRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsServicesRoute: typeof AppSettingsServicesRoute
  AppSettingsSystemRoute: typeof AppSettingsSystemRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppAccountFeedbackPackagesRoute: typeof AppAccountFeedbackPackagesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRouteWithChildren,
  AppFeedbackRoute: AppFeedbackRouteWithChildren,
  AppFollowUpRoute: AppFollowUpRoute,
  AppInterviewsRoute: AppInterviewsRouteWithChildren,
  AppPackagesRoute: AppPackagesRoute,
  AppRecoveryRoute: AppRecoveryRouteWithChildren,
  AppSurveysRoute: AppSurveysRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAccountBillingRoute: AppAccountBillingRoute,
  AppAccountPackagesRoute: AppAccountPackagesRoute,
  AppAccountSupportRoute: AppAccountSupportRouteWithChildren,
  AppAccountUsageRoute: AppAccountUsageRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppCampaignsSendRoute: AppCampaignsSendRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsOptOutRoute: AppSettingsOptOutRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsServicesRoute: AppSettingsServicesRoute,
  AppSettingsSystemRoute: AppSettingsSystemRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppAccountFeedbackPackagesRoute: AppAccountFeedbackPackagesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  BookTokenRoute: BookTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
