/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as BookTokenRouteImport } from './routes/book.$token'
import { Route as AppSurveysRouteImport } from './routes/_app.surveys'
import { Route as AppRecoveryRouteImport } from './routes/_app.recovery'
import { Route as AppInterviewsRouteImport } from './routes/_app.interviews'
import { Route as AppFollowUpRouteImport } from './routes/_app.follow-up'
import { Route as AppSurveysIndexRouteImport } from './routes/_app.surveys.index'
import { Route as AppRecoveryIndexRouteImport } from './routes/_app.recovery.index'
import { Route as AppInterviewsIndexRouteImport } from './routes/_app.interviews.index'
import { Route as AppSurveysResultsRouteImport } from './routes/_app.surveys.results'
import { Route as AppSurveysReportsRouteImport } from './routes/_app.surveys.reports'
import { Route as AppSurveysNewRouteImport } from './routes/_app.surveys.new'
import { Route as AppSurveysIdRouteImport } from './routes/_app.surveys.$id'
import { Route as AppSettingsTeamRouteImport } from './routes/_app.settings.team'
import { Route as AppSettingsSystemRouteImport } from './routes/_app.settings.system'
import { Route as AppSettingsServicesRouteImport } from './routes/_app.settings.services'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppSettingsOptOutRouteImport } from './routes/_app.settings.opt-out'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app.settings.integrations'
import { Route as AppSettingsAuditRouteImport } from './routes/_app.settings.audit'
import { Route as AppRecoveryRecallRouteImport } from './routes/_app.recovery.recall'
import { Route as AppRecoveryOffersRouteImport } from './routes/_app.recovery.offers'
import { Route as AppRecoveryNoShowRouteImport } from './routes/_app.recovery.no-show'
import { Route as AppRecoveryEmergencyRouteImport } from './routes/_app.recovery.emergency'
import { Route as AppInterviewsResultsRouteImport } from './routes/_app.interviews.results'
import { Route as AppInterviewsReportsRouteImport } from './routes/_app.interviews.reports'
import { Route as AppInterviewsNewRouteImport } from './routes/_app.interviews.new'
import { Route as AppAccountSupportRouteImport } from './routes/_app.account.support'
import { Route as AppAccountPackagesRouteImport } from './routes/_app.account.packages'
import { Route as AppAccountBillingRouteImport } from './routes/_app.account.billing'
import { Route as AppInterviewsResultsIndexRouteImport } from './routes/_app.interviews.results.index'
import { Route as AppAccountSupportIndexRouteImport } from './routes/_app.account.support.index'
import { Route as AppInterviewsResultsOrderIdRouteImport } from './routes/_app.interviews.results.$orderId'
import { Route as AppAccountSupportTicketsRouteImport } from './routes/_app.account.support.tickets'
import { Route as AppAccountSupportFaqRouteImport } from './routes/_app.account.support.faq'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const BookTokenRoute = BookTokenRouteImport.update({
  id: '/book/$token',
  path: '/book/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSurveysRoute = AppSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoveryRoute = AppRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpRoute = AppFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIndexRoute = AppSurveysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppRecoveryIndexRoute = AppRecoveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppSurveysResultsRoute = AppSurveysResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppSurveysReportsRoute = AppSurveysReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppSurveysNewRoute = AppSurveysNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppSurveysIdRoute = AppSurveysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSurveysRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSystemRoute = AppSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsServicesRoute = AppSettingsServicesRouteImport.update({
  id: '/settings/services',
  path: '/settings/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOptOutRoute = AppSettingsOptOutRouteImport.update({
  id: '/settings/opt-out',
  path: '/settings/opt-out',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoveryRecallRoute = AppRecoveryRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppRecoveryOffersRoute = AppRecoveryOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppRecoveryNoShowRoute = AppRecoveryNoShowRouteImport.update({
  id: '/no-show',
  path: '/no-show',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppRecoveryEmergencyRoute = AppRecoveryEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppInterviewsResultsRoute = AppInterviewsResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppInterviewsReportsRoute = AppInterviewsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppInterviewsNewRoute = AppInterviewsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppAccountSupportRoute = AppAccountSupportRouteImport.update({
  id: '/account/support',
  path: '/account/support',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountPackagesRoute = AppAccountPackagesRouteImport.update({
  id: '/account/packages',
  path: '/account/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountBillingRoute = AppAccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsResultsIndexRoute =
  AppInterviewsResultsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInterviewsResultsRoute,
  } as any)
const AppAccountSupportIndexRoute = AppAccountSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountSupportRoute,
} as any)
const AppInterviewsResultsOrderIdRoute =
  AppInterviewsResultsOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AppInterviewsResultsRoute,
  } as any)
const AppAccountSupportTicketsRoute =
  AppAccountSupportTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AppAccountSupportRoute,
  } as any)
const AppAccountSupportFaqRoute = AppAccountSupportFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppAccountSupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/follow-up': typeof AppFollowUpRoute
  '/interviews': typeof AppInterviewsRouteWithChildren
  '/recovery': typeof AppRecoveryRouteWithChildren
  '/surveys': typeof AppSurveysRouteWithChildren
  '/book/$token': typeof BookTokenRoute
  '/account/billing': typeof AppAccountBillingRoute
  '/account/packages': typeof AppAccountPackagesRoute
  '/account/support': typeof AppAccountSupportRouteWithChildren
  '/interviews/new': typeof AppInterviewsNewRoute
  '/interviews/reports': typeof AppInterviewsReportsRoute
  '/interviews/results': typeof AppInterviewsResultsRouteWithChildren
  '/recovery/emergency': typeof AppRecoveryEmergencyRoute
  '/recovery/no-show': typeof AppRecoveryNoShowRoute
  '/recovery/offers': typeof AppRecoveryOffersRoute
  '/recovery/recall': typeof AppRecoveryRecallRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/opt-out': typeof AppSettingsOptOutRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/services': typeof AppSettingsServicesRoute
  '/settings/system': typeof AppSettingsSystemRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/surveys/$id': typeof AppSurveysIdRoute
  '/surveys/new': typeof AppSurveysNewRoute
  '/surveys/reports': typeof AppSurveysReportsRoute
  '/surveys/results': typeof AppSurveysResultsRoute
  '/interviews/': typeof AppInterviewsIndexRoute
  '/recovery/': typeof AppRecoveryIndexRoute
  '/surveys/': typeof AppSurveysIndexRoute
  '/account/support/faq': typeof AppAccountSupportFaqRoute
  '/account/support/tickets': typeof AppAccountSupportTicketsRoute
  '/interviews/results/$orderId': typeof AppInterviewsResultsOrderIdRoute
  '/account/support/': typeof AppAccountSupportIndexRoute
  '/interviews/results/': typeof AppInterviewsResultsIndexRoute
}
export interface FileRoutesByTo {
  '/follow-up': typeof AppFollowUpRoute
  '/book/$token': typeof BookTokenRoute
  '/': typeof AppIndexRoute
  '/account/billing': typeof AppAccountBillingRoute
  '/account/packages': typeof AppAccountPackagesRoute
  '/interviews/new': typeof AppInterviewsNewRoute
  '/interviews/reports': typeof AppInterviewsReportsRoute
  '/recovery/emergency': typeof AppRecoveryEmergencyRoute
  '/recovery/no-show': typeof AppRecoveryNoShowRoute
  '/recovery/offers': typeof AppRecoveryOffersRoute
  '/recovery/recall': typeof AppRecoveryRecallRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/opt-out': typeof AppSettingsOptOutRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/services': typeof AppSettingsServicesRoute
  '/settings/system': typeof AppSettingsSystemRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/surveys/$id': typeof AppSurveysIdRoute
  '/surveys/new': typeof AppSurveysNewRoute
  '/surveys/reports': typeof AppSurveysReportsRoute
  '/surveys/results': typeof AppSurveysResultsRoute
  '/interviews': typeof AppInterviewsIndexRoute
  '/recovery': typeof AppRecoveryIndexRoute
  '/surveys': typeof AppSurveysIndexRoute
  '/account/support/faq': typeof AppAccountSupportFaqRoute
  '/account/support/tickets': typeof AppAccountSupportTicketsRoute
  '/interviews/results/$orderId': typeof AppInterviewsResultsOrderIdRoute
  '/account/support': typeof AppAccountSupportIndexRoute
  '/interviews/results': typeof AppInterviewsResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/follow-up': typeof AppFollowUpRoute
  '/_app/interviews': typeof AppInterviewsRouteWithChildren
  '/_app/recovery': typeof AppRecoveryRouteWithChildren
  '/_app/surveys': typeof AppSurveysRouteWithChildren
  '/book/$token': typeof BookTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/billing': typeof AppAccountBillingRoute
  '/_app/account/packages': typeof AppAccountPackagesRoute
  '/_app/account/support': typeof AppAccountSupportRouteWithChildren
  '/_app/interviews/new': typeof AppInterviewsNewRoute
  '/_app/interviews/reports': typeof AppInterviewsReportsRoute
  '/_app/interviews/results': typeof AppInterviewsResultsRouteWithChildren
  '/_app/recovery/emergency': typeof AppRecoveryEmergencyRoute
  '/_app/recovery/no-show': typeof AppRecoveryNoShowRoute
  '/_app/recovery/offers': typeof AppRecoveryOffersRoute
  '/_app/recovery/recall': typeof AppRecoveryRecallRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/opt-out': typeof AppSettingsOptOutRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/services': typeof AppSettingsServicesRoute
  '/_app/settings/system': typeof AppSettingsSystemRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/surveys/$id': typeof AppSurveysIdRoute
  '/_app/surveys/new': typeof AppSurveysNewRoute
  '/_app/surveys/reports': typeof AppSurveysReportsRoute
  '/_app/surveys/results': typeof AppSurveysResultsRoute
  '/_app/interviews/': typeof AppInterviewsIndexRoute
  '/_app/recovery/': typeof AppRecoveryIndexRoute
  '/_app/surveys/': typeof AppSurveysIndexRoute
  '/_app/account/support/faq': typeof AppAccountSupportFaqRoute
  '/_app/account/support/tickets': typeof AppAccountSupportTicketsRoute
  '/_app/interviews/results/$orderId': typeof AppInterviewsResultsOrderIdRoute
  '/_app/account/support/': typeof AppAccountSupportIndexRoute
  '/_app/interviews/results/': typeof AppInterviewsResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/follow-up'
    | '/interviews'
    | '/recovery'
    | '/surveys'
    | '/book/$token'
    | '/account/billing'
    | '/account/packages'
    | '/account/support'
    | '/interviews/new'
    | '/interviews/reports'
    | '/interviews/results'
    | '/recovery/emergency'
    | '/recovery/no-show'
    | '/recovery/offers'
    | '/recovery/recall'
    | '/settings/audit'
    | '/settings/integrations'
    | '/settings/opt-out'
    | '/settings/profile'
    | '/settings/services'
    | '/settings/system'
    | '/settings/team'
    | '/surveys/$id'
    | '/surveys/new'
    | '/surveys/reports'
    | '/surveys/results'
    | '/interviews/'
    | '/recovery/'
    | '/surveys/'
    | '/account/support/faq'
    | '/account/support/tickets'
    | '/interviews/results/$orderId'
    | '/account/support/'
    | '/interviews/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/follow-up'
    | '/book/$token'
    | '/'
    | '/account/billing'
    | '/account/packages'
    | '/interviews/new'
    | '/interviews/reports'
    | '/recovery/emergency'
    | '/recovery/no-show'
    | '/recovery/offers'
    | '/recovery/recall'
    | '/settings/audit'
    | '/settings/integrations'
    | '/settings/opt-out'
    | '/settings/profile'
    | '/settings/services'
    | '/settings/system'
    | '/settings/team'
    | '/surveys/$id'
    | '/surveys/new'
    | '/surveys/reports'
    | '/surveys/results'
    | '/interviews'
    | '/recovery'
    | '/surveys'
    | '/account/support/faq'
    | '/account/support/tickets'
    | '/interviews/results/$orderId'
    | '/account/support'
    | '/interviews/results'
  id:
    | '__root__'
    | '/_app'
    | '/_app/follow-up'
    | '/_app/interviews'
    | '/_app/recovery'
    | '/_app/surveys'
    | '/book/$token'
    | '/_app/'
    | '/_app/account/billing'
    | '/_app/account/packages'
    | '/_app/account/support'
    | '/_app/interviews/new'
    | '/_app/interviews/reports'
    | '/_app/interviews/results'
    | '/_app/recovery/emergency'
    | '/_app/recovery/no-show'
    | '/_app/recovery/offers'
    | '/_app/recovery/recall'
    | '/_app/settings/audit'
    | '/_app/settings/integrations'
    | '/_app/settings/opt-out'
    | '/_app/settings/profile'
    | '/_app/settings/services'
    | '/_app/settings/system'
    | '/_app/settings/team'
    | '/_app/surveys/$id'
    | '/_app/surveys/new'
    | '/_app/surveys/reports'
    | '/_app/surveys/results'
    | '/_app/interviews/'
    | '/_app/recovery/'
    | '/_app/surveys/'
    | '/_app/account/support/faq'
    | '/_app/account/support/tickets'
    | '/_app/interviews/results/$orderId'
    | '/_app/account/support/'
    | '/_app/interviews/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  BookTokenRoute: typeof BookTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$token': {
      id: '/book/$token'
      path: '/book/$token'
      fullPath: '/book/$token'
      preLoaderRoute: typeof BookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/surveys': {
      id: '/_app/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof AppSurveysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recovery': {
      id: '/_app/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof AppRecoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-up': {
      id: '/_app/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof AppFollowUpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/': {
      id: '/_app/surveys/'
      path: '/'
      fullPath: '/surveys/'
      preLoaderRoute: typeof AppSurveysIndexRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/recovery/': {
      id: '/_app/recovery/'
      path: '/'
      fullPath: '/recovery/'
      preLoaderRoute: typeof AppRecoveryIndexRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/interviews/': {
      id: '/_app/interviews/'
      path: '/'
      fullPath: '/interviews/'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/surveys/results': {
      id: '/_app/surveys/results'
      path: '/results'
      fullPath: '/surveys/results'
      preLoaderRoute: typeof AppSurveysResultsRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/surveys/reports': {
      id: '/_app/surveys/reports'
      path: '/reports'
      fullPath: '/surveys/reports'
      preLoaderRoute: typeof AppSurveysReportsRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/surveys/new': {
      id: '/_app/surveys/new'
      path: '/new'
      fullPath: '/surveys/new'
      preLoaderRoute: typeof AppSurveysNewRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/surveys/$id': {
      id: '/_app/surveys/$id'
      path: '/$id'
      fullPath: '/surveys/$id'
      preLoaderRoute: typeof AppSurveysIdRouteImport
      parentRoute: typeof AppSurveysRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/system': {
      id: '/_app/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AppSettingsSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/services': {
      id: '/_app/settings/services'
      path: '/settings/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof AppSettingsServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/opt-out': {
      id: '/_app/settings/opt-out'
      path: '/settings/opt-out'
      fullPath: '/settings/opt-out'
      preLoaderRoute: typeof AppSettingsOptOutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recovery/recall': {
      id: '/_app/recovery/recall'
      path: '/recall'
      fullPath: '/recovery/recall'
      preLoaderRoute: typeof AppRecoveryRecallRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/recovery/offers': {
      id: '/_app/recovery/offers'
      path: '/offers'
      fullPath: '/recovery/offers'
      preLoaderRoute: typeof AppRecoveryOffersRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/recovery/no-show': {
      id: '/_app/recovery/no-show'
      path: '/no-show'
      fullPath: '/recovery/no-show'
      preLoaderRoute: typeof AppRecoveryNoShowRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/recovery/emergency': {
      id: '/_app/recovery/emergency'
      path: '/emergency'
      fullPath: '/recovery/emergency'
      preLoaderRoute: typeof AppRecoveryEmergencyRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/interviews/results': {
      id: '/_app/interviews/results'
      path: '/results'
      fullPath: '/interviews/results'
      preLoaderRoute: typeof AppInterviewsResultsRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/interviews/reports': {
      id: '/_app/interviews/reports'
      path: '/reports'
      fullPath: '/interviews/reports'
      preLoaderRoute: typeof AppInterviewsReportsRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/interviews/new': {
      id: '/_app/interviews/new'
      path: '/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof AppInterviewsNewRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/account/support': {
      id: '/_app/account/support'
      path: '/account/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AppAccountSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/packages': {
      id: '/_app/account/packages'
      path: '/account/packages'
      fullPath: '/account/packages'
      preLoaderRoute: typeof AppAccountPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/billing': {
      id: '/_app/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AppAccountBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/results/': {
      id: '/_app/interviews/results/'
      path: '/'
      fullPath: '/interviews/results/'
      preLoaderRoute: typeof AppInterviewsResultsIndexRouteImport
      parentRoute: typeof AppInterviewsResultsRoute
    }
    '/_app/account/support/': {
      id: '/_app/account/support/'
      path: '/'
      fullPath: '/account/support/'
      preLoaderRoute: typeof AppAccountSupportIndexRouteImport
      parentRoute: typeof AppAccountSupportRoute
    }
    '/_app/interviews/results/$orderId': {
      id: '/_app/interviews/results/$orderId'
      path: '/$orderId'
      fullPath: '/interviews/results/$orderId'
      preLoaderRoute: typeof AppInterviewsResultsOrderIdRouteImport
      parentRoute: typeof AppInterviewsResultsRoute
    }
    '/_app/account/support/tickets': {
      id: '/_app/account/support/tickets'
      path: '/tickets'
      fullPath: '/account/support/tickets'
      preLoaderRoute: typeof AppAccountSupportTicketsRouteImport
      parentRoute: typeof AppAccountSupportRoute
    }
    '/_app/account/support/faq': {
      id: '/_app/account/support/faq'
      path: '/faq'
      fullPath: '/account/support/faq'
      preLoaderRoute: typeof AppAccountSupportFaqRouteImport
      parentRoute: typeof AppAccountSupportRoute
    }
  }
}

interface AppInterviewsResultsRouteChildren {
  AppInterviewsResultsOrderIdRoute: typeof AppInterviewsResultsOrderIdRoute
  AppInterviewsResultsIndexRoute: typeof AppInterviewsResultsIndexRoute
}

const AppInterviewsResultsRouteChildren: AppInterviewsResultsRouteChildren = {
  AppInterviewsResultsOrderIdRoute: AppInterviewsResultsOrderIdRoute,
  AppInterviewsResultsIndexRoute: AppInterviewsResultsIndexRoute,
}

const AppInterviewsResultsRouteWithChildren =
  AppInterviewsResultsRoute._addFileChildren(AppInterviewsResultsRouteChildren)

interface AppInterviewsRouteChildren {
  AppInterviewsNewRoute: typeof AppInterviewsNewRoute
  AppInterviewsReportsRoute: typeof AppInterviewsReportsRoute
  AppInterviewsResultsRoute: typeof AppInterviewsResultsRouteWithChildren
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
}

const AppInterviewsRouteChildren: AppInterviewsRouteChildren = {
  AppInterviewsNewRoute: AppInterviewsNewRoute,
  AppInterviewsReportsRoute: AppInterviewsReportsRoute,
  AppInterviewsResultsRoute: AppInterviewsResultsRouteWithChildren,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
}

const AppInterviewsRouteWithChildren = AppInterviewsRoute._addFileChildren(
  AppInterviewsRouteChildren,
)

interface AppRecoveryRouteChildren {
  AppRecoveryEmergencyRoute: typeof AppRecoveryEmergencyRoute
  AppRecoveryNoShowRoute: typeof AppRecoveryNoShowRoute
  AppRecoveryOffersRoute: typeof AppRecoveryOffersRoute
  AppRecoveryRecallRoute: typeof AppRecoveryRecallRoute
  AppRecoveryIndexRoute: typeof AppRecoveryIndexRoute
}

const AppRecoveryRouteChildren: AppRecoveryRouteChildren = {
  AppRecoveryEmergencyRoute: AppRecoveryEmergencyRoute,
  AppRecoveryNoShowRoute: AppRecoveryNoShowRoute,
  AppRecoveryOffersRoute: AppRecoveryOffersRoute,
  AppRecoveryRecallRoute: AppRecoveryRecallRoute,
  AppRecoveryIndexRoute: AppRecoveryIndexRoute,
}

const AppRecoveryRouteWithChildren = AppRecoveryRoute._addFileChildren(
  AppRecoveryRouteChildren,
)

interface AppSurveysRouteChildren {
  AppSurveysIdRoute: typeof AppSurveysIdRoute
  AppSurveysNewRoute: typeof AppSurveysNewRoute
  AppSurveysReportsRoute: typeof AppSurveysReportsRoute
  AppSurveysResultsRoute: typeof AppSurveysResultsRoute
  AppSurveysIndexRoute: typeof AppSurveysIndexRoute
}

const AppSurveysRouteChildren: AppSurveysRouteChildren = {
  AppSurveysIdRoute: AppSurveysIdRoute,
  AppSurveysNewRoute: AppSurveysNewRoute,
  AppSurveysReportsRoute: AppSurveysReportsRoute,
  AppSurveysResultsRoute: AppSurveysResultsRoute,
  AppSurveysIndexRoute: AppSurveysIndexRoute,
}

const AppSurveysRouteWithChildren = AppSurveysRoute._addFileChildren(
  AppSurveysRouteChildren,
)

interface AppAccountSupportRouteChildren {
  AppAccountSupportFaqRoute: typeof AppAccountSupportFaqRoute
  AppAccountSupportTicketsRoute: typeof AppAccountSupportTicketsRoute
  AppAccountSupportIndexRoute: typeof AppAccountSupportIndexRoute
}

const AppAccountSupportRouteChildren: AppAccountSupportRouteChildren = {
  AppAccountSupportFaqRoute: AppAccountSupportFaqRoute,
  AppAccountSupportTicketsRoute: AppAccountSupportTicketsRoute,
  AppAccountSupportIndexRoute: AppAccountSupportIndexRoute,
}

const AppAccountSupportRouteWithChildren =
  AppAccountSupportRoute._addFileChildren(AppAccountSupportRouteChildren)

interface AppRouteChildren {
  AppFollowUpRoute: typeof AppFollowUpRoute
  AppInterviewsRoute: typeof AppInterviewsRouteWithChildren
  AppRecoveryRoute: typeof AppRecoveryRouteWithChildren
  AppSurveysRoute: typeof AppSurveysRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAccountBillingRoute: typeof AppAccountBillingRoute
  AppAccountPackagesRoute: typeof AppAccountPackagesRoute
  AppAccountSupportRoute: typeof AppAccountSupportRouteWithChildren
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsOptOutRoute: typeof AppSettingsOptOutRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsServicesRoute: typeof AppSettingsServicesRoute
  AppSettingsSystemRoute: typeof AppSettingsSystemRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFollowUpRoute: AppFollowUpRoute,
  AppInterviewsRoute: AppInterviewsRouteWithChildren,
  AppRecoveryRoute: AppRecoveryRouteWithChildren,
  AppSurveysRoute: AppSurveysRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAccountBillingRoute: AppAccountBillingRoute,
  AppAccountPackagesRoute: AppAccountPackagesRoute,
  AppAccountSupportRoute: AppAccountSupportRouteWithChildren,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsOptOutRoute: AppSettingsOptOutRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsServicesRoute: AppSettingsServicesRoute,
  AppSettingsSystemRoute: AppSettingsSystemRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  BookTokenRoute: BookTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
