#!/usr/bin/env bash
# One-time VPS setup: install voxbulk-celery in supervisor (replaces retover-celery).
#
# Usage on VPS:
#   cd /www/voxbulk
#   chmod +x scripts/vps-setup-celery.sh scripts/run-celery-worker.sh
#   sudo bash scripts/vps-setup-celery.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
API_DIR="$ROOT/voxbulk-api"
CELERY_BIN="$API_DIR/.venv/bin/celery"
RUN_SCRIPT="$ROOT/scripts/run-celery-worker.sh"
TEMPLATE="$API_DIR/supervisor/voxbulk.conf"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[celery-setup]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*" >&2; }
fail()  { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

[[ -d "$API_DIR" ]] || fail "API dir not found: $API_DIR"
[[ -f "$RUN_SCRIPT" ]] || fail "Missing $RUN_SCRIPT"

chmod +x "$RUN_SCRIPT"

if [[ ! -x "$CELERY_BIN" ]]; then
  info "Installing Python deps (celery) into venv …"
  cd "$API_DIR"
  if [[ ! -d .venv ]]; then
    python3 -m venv .venv
  fi
  # shellcheck disable=SC1091
  source .venv/bin/activate
  pip install -q -U pip
  pip install -q -r requirements.txt
fi

[[ -x "$CELERY_BIN" ]] || fail "Celery still missing after pip install: $CELERY_BIN"

info "Celery binary: $CELERY_BIN ($("$CELERY_BIN" --version 2>/dev/null || echo unknown))"

if ! redis-cli ping >/dev/null 2>&1; then
  warn "Redis did not respond to PING — Celery needs Redis (CELERY_BROKER_URL in .env)"
else
  info "Redis OK"
fi

if ! command -v supervisorctl >/dev/null 2>&1; then
  fail "supervisorctl not found — install supervisor: apt-get install supervisor"
fi

SUPERVISOR_D="/etc/supervisor/conf.d"
DEST="$SUPERVISOR_D/voxbulk-celery.conf"

if [[ ! -d "$SUPERVISOR_D" ]]; then
  fail "Supervisor conf.d not found at $SUPERVISOR_D"
fi

info "Writing $DEST (paths: ROOT=$ROOT)"
cat >"/tmp/voxbulk-celery.conf" <<EOF
; VoxBulk Celery worker — generated by vps-setup-celery.sh
[program:voxbulk-celery]
directory=$API_DIR
command=$RUN_SCRIPT
autostart=true
autorestart=true
startretries=5
startsecs=3
stopwaitsecs=30
stdout_logfile=/tmp/voxbulk-celery.log
stderr_logfile=/tmp/voxbulk-celery.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
environment=PYTHONUNBUFFERED="1"
EOF

sudo cp "/tmp/voxbulk-celery.conf" "$DEST"
rm -f "/tmp/voxbulk-celery.conf"

# Retire legacy retover program names
for legacy in retover-celery.conf retover.conf voxbulk-retover-celery.conf; do
  if [[ -f "$SUPERVISOR_D/$legacy" ]]; then
    warn "Removing legacy supervisor config: $SUPERVISOR_D/$legacy"
    sudo rm -f "$SUPERVISOR_D/$legacy"
  fi
done

if supervisorctl status retover-celery >/dev/null 2>&1; then
  warn "Stopping legacy retover-celery …"
  sudo supervisorctl stop retover-celery 2>/dev/null || true
fi

info "Reloading supervisor …"
sudo supervisorctl reread
sudo supervisorctl update

info "Starting voxbulk-celery …"
sudo supervisorctl start voxbulk-celery || sudo supervisorctl restart voxbulk-celery

sleep 2
sudo supervisorctl status voxbulk-celery

cd "$API_DIR"
# shellcheck disable=SC1091
source .venv/bin/activate
if celery -A app.workers.celery_app:celery_app inspect ping >/dev/null 2>&1; then
  info "Worker ping OK — survey.transcribe_voice_note tasks can run"
else
  warn "Worker ping failed — check: tail -50 /tmp/voxbulk-celery.err.log"
  warn "Ensure CELERY_BROKER_URL in voxbulk-api/.env points at running Redis"
fi

cat <<NOTES

══════════════════════════════════════════════════════════════
Celery setup complete
══════════════════════════════════════════════════════════════
  Status:    sudo supervisorctl status voxbulk-celery
  Logs:      tail -f /tmp/voxbulk-celery.log
  Restart:   sudo supervisorctl restart voxbulk-celery
  Or:        cd /www/voxbulk && ./vox.sh restart

Retry stuck voice notes (admin session):
  POST /admin/wa-survey/voice-notes/{job_id}/retry

Required for WA survey voice-note transcription (not optional).
NOTES
