#!/usr/bin/env bash
# Idempotent VPS install: Cypht multi-account webmail at https://allmail.voxbulk.com
#
# Prerequisites:
#   - DNS A record allmail.voxbulk.com → this VPS (already resolves in production)
#   - Docker + docker compose plugin (script installs if missing)
#   - aaPanel nginx (writes vhost under /www/server/panel/vhost/nginx/)
#
# Usage on VPS:
#   cd /www/voxbulk
#   git pull origin main
#   sudo bash scripts/vps-setup-cypht.sh
#
# Optional env:
#   CYPHT_ADMIN_USER=admin
#   CYPHT_ADMIN_PASSWORD=...     # auto-generated if omitted (printed once)
#   CYPHT_HOST_PORT=8090
#   CYPHT_SKIP_SSL=1             # skip certbot / leave existing SSL paths
#   CYPHT_SKIP_NGINX=1           # only start Docker stack
#   CYPHT_SYSTEMD_SKIP_START=1   # write unit but do not start
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_SRC="$ROOT/scripts/cypht/docker-compose.yml"
NGINX_TMPL="$ROOT/scripts/cypht/nginx-allmail.voxbulk.com.conf.template"
DATA_DIR="${CYPHT_DATA_DIR:-/www/voxbulk/data/cypht}"
ENV_FILE="$DATA_DIR/.env"
COMPOSE_LINK="$DATA_DIR/docker-compose.yml"
UNIT_PATH="/etc/systemd/system/voxbulk-cypht.service"
NGINX_VHOST="${CYPHT_NGINX_VHOST:-/www/server/panel/vhost/nginx/allmail.voxbulk.com.conf}"
DOMAIN="allmail.voxbulk.com"
HOST_PORT="${CYPHT_HOST_PORT:-8090}"
ADMIN_USER="${CYPHT_ADMIN_USER:-admin}"
LOG_DIR="/var/log/voxbulk"
CYPHT_LOG="$LOG_DIR/cypht.log"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
info()  { echo -e "${GREEN}[cypht]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*" >&2; }
fail()  { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

[[ "$(id -u)" -eq 0 ]] || fail "Run with sudo: sudo bash scripts/vps-setup-cypht.sh"
[[ -f "$COMPOSE_SRC" ]] || fail "Missing $COMPOSE_SRC — git pull origin main first"
[[ -f "$NGINX_TMPL" ]] || fail "Missing $NGINX_TMPL"

rand_pw() {
  # URL-safe-ish password, 24 chars
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '/+=' | head -c 24
  else
    head -c 48 /dev/urandom | base64 | tr -d '/+=' | head -c 24
  fi
}

ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    info "Docker + compose OK"
    return 0
  fi
  info "Installing Docker Engine + compose plugin…"
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg >/dev/null
    if [[ ! -f /etc/apt/keyrings/docker.gpg ]]; then
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      chmod a+r /etc/apt/keyrings/docker.gpg
    fi
    . /etc/os-release
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
      > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin >/dev/null
  else
    fail "apt-get not found — install Docker manually, then re-run"
  fi
  systemctl enable --now docker
  docker compose version >/dev/null 2>&1 || fail "docker compose still missing after install"
}

ensure_env() {
  mkdir -p "$DATA_DIR/data"/{mysql,users,attachments,app_data,log/nginx,log/php}
  chmod 750 "$DATA_DIR"
  if [[ -f "$ENV_FILE" ]]; then
    info "Reusing existing $ENV_FILE"
    # shellcheck disable=SC1090
    set -a; source "$ENV_FILE"; set +a
    HOST_PORT="${CYPHT_HOST_PORT:-$HOST_PORT}"
    ADMIN_USER="${CYPHT_ADMIN_USER:-$ADMIN_USER}"
    return 0
  fi

  local admin_pw db_pw root_pw
  admin_pw="${CYPHT_ADMIN_PASSWORD:-$(rand_pw)}"
  db_pw="${CYPHT_DB_PASSWORD:-$(rand_pw)}"
  root_pw="${CYPHT_DB_ROOT_PASSWORD:-$(rand_pw)}"

  cat > "$ENV_FILE" <<EOF
# Generated by vps-setup-cypht.sh — keep private (chmod 600)
CYPHT_HOST_PORT=${HOST_PORT}
CYPHT_COOKIE_DOMAIN=${DOMAIN}
CYPHT_DISABLE_ORIGIN_CHECK=true

CYPHT_ADMIN_USER=${ADMIN_USER}
CYPHT_ADMIN_PASSWORD=${admin_pw}

CYPHT_DB_NAME=cypht
CYPHT_DB_USER=cypht
CYPHT_DB_PASSWORD=${db_pw}
CYPHT_DB_ROOT_PASSWORD=${root_pw}
EOF
  chmod 600 "$ENV_FILE"
  info "Wrote credentials to $ENV_FILE"
  echo ""
  echo "========== Cypht login (save now) =========="
  echo "URL:      https://${DOMAIN}"
  echo "User:     ${ADMIN_USER}"
  echo "Password: ${admin_pw}"
  echo "============================================"
  echo ""
}

link_compose() {
  # Compose file lives in DATA_DIR so volumes ./data/* resolve next to runtime state.
  cp -a "$COMPOSE_SRC" "$COMPOSE_LINK"
  # Relative volume paths in compose → DATA_DIR/data/*
  # compose file uses ./data/... which is correct when cwd is DATA_DIR.
}

install_domain_cert() {
  # Always use a cert whose CN/SAN is this domain — never borrow voxbulk.com/admin certs
  # (wrong SNI fallthrough previously served Admin UI for allmail).
  local ssldir="/www/server/panel/vhost/cert/${DOMAIN}"
  local webroot="/www/wwwroot/${DOMAIN}"
  mkdir -p "$ssldir" "$webroot/.well-known/acme-challenge"

  if [[ -f "$ssldir/fullchain.pem" && -f "$ssldir/privkey.pem" && ! -L "$ssldir/fullchain.pem" ]]; then
    if openssl x509 -in "$ssldir/fullchain.pem" -noout -checkend 86400 >/dev/null 2>&1; then
      local san
      san="$(openssl x509 -in "$ssldir/fullchain.pem" -noout -text 2>/dev/null | tr -d '\n' || true)"
      if [[ "$san" == *"$DOMAIN"* ]]; then
        SSL_CERT="$ssldir/fullchain.pem"
        SSL_KEY="$ssldir/privkey.pem"
        info "Using existing SSL cert: $SSL_CERT"
        return 0
      fi
    fi
  fi

  if command -v certbot >/dev/null 2>&1; then
    info "Requesting Let's Encrypt cert for ${DOMAIN}…"
    if certbot certonly --webroot -w "$webroot" -d "$DOMAIN" --non-interactive --agree-tos \
        --register-unsafely-without-email --keep-until-expiring 2>/tmp/cypht-certbot.log; then
      # Remove dangling relative symlinks certbot may drop under aaPanel cert dir
      rm -f "$ssldir/fullchain.pem" "$ssldir/privkey.pem"
      cp -L "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" "$ssldir/fullchain.pem"
      cp -L "/etc/letsencrypt/live/${DOMAIN}/privkey.pem" "$ssldir/privkey.pem"
      SSL_CERT="$ssldir/fullchain.pem"
      SSL_KEY="$ssldir/privkey.pem"
      info "Installed Let's Encrypt cert into $ssldir"
      return 0
    fi
    warn "certbot failed — see /tmp/cypht-certbot.log"
  fi

  warn "Creating short-term self-signed cert (replace via aaPanel → SSL)"
  rm -f "$ssldir/fullchain.pem" "$ssldir/privkey.pem"
  openssl req -x509 -nodes -newkey rsa:2048 -days 30 \
    -keyout "$ssldir/privkey.pem" \
    -out "$ssldir/fullchain.pem" \
    -subj "/CN=${DOMAIN}" >/dev/null 2>&1
  SSL_CERT="$ssldir/fullchain.pem"
  SSL_KEY="$ssldir/privkey.pem"
  return 0
}

register_aapanel_site() {
  local db="/www/server/panel/data/default.db"
  local wwwroot="/www/wwwroot/${DOMAIN}"
  [[ -f "$db" ]] || { warn "aaPanel DB missing — skip panel registration"; return 0; }
  command -v sqlite3 >/dev/null 2>&1 || { warn "sqlite3 missing — skip panel registration"; return 0; }

  mkdir -p "$wwwroot" \
    "/www/server/panel/vhost/nginx/extension/${DOMAIN}" \
    /www/server/panel/vhost/nginx/well-known \
    /www/server/panel/vhost/rewrite
  echo "Cypht multi-account webmail" > "$wwwroot/index.html"
  cat > "/www/server/panel/vhost/nginx/well-known/${DOMAIN}.conf" <<EOF
location ^~ /.well-known/acme-challenge/ {
    root ${wwwroot};
    default_type text/plain;
    allow all;
}
EOF
  touch "/www/server/panel/vhost/rewrite/${DOMAIN}.conf"

  local site_id now
  now="$(date '+%Y-%m-%d %H:%M:%S')"
  site_id="$(sqlite3 "$db" "SELECT id FROM sites WHERE name='${DOMAIN}' LIMIT 1;")"
  if [[ -z "$site_id" ]]; then
    sqlite3 "$db" "INSERT INTO sites(name,path,status,\"index\",ps,addtime,type_id,edate,project_type) VALUES('${DOMAIN}','${wwwroot}','1','index.html','Cypht multi-account webmail','${now}',0,'0000-00-00','PHP');"
    site_id="$(sqlite3 "$db" "SELECT id FROM sites WHERE name='${DOMAIN}' LIMIT 1;")"
    info "Registered aaPanel site id=${site_id}"
  else
    sqlite3 "$db" "UPDATE sites SET status='1', path='${wwwroot}', ps='Cypht multi-account webmail' WHERE id=${site_id};"
    info "Updated aaPanel site id=${site_id}"
  fi

  local dom_id
  dom_id="$(sqlite3 "$db" "SELECT id FROM domain WHERE name='${DOMAIN}' LIMIT 1;")"
  if [[ -z "$dom_id" ]]; then
    sqlite3 "$db" "INSERT INTO domain(pid,name,port,addtime) VALUES(${site_id},'${DOMAIN}',80,'${now}');"
  else
    sqlite3 "$db" "UPDATE domain SET pid=${site_id} WHERE id=${dom_id};"
  fi
}

write_nginx() {
  if [[ "${CYPHT_SKIP_NGINX:-0}" == "1" ]]; then
    warn "CYPHT_SKIP_NGINX=1 — skip nginx vhost"
    return 0
  fi
  command -v nginx >/dev/null 2>&1 || fail "nginx not found (aaPanel nginx expected)"

  register_aapanel_site

  # Write HTTP+ACME vhost first so certbot webroot can succeed, then SSL paths.
  SSL_CERT="/www/server/panel/vhost/cert/${DOMAIN}/fullchain.pem"
  SSL_KEY="/www/server/panel/vhost/cert/${DOMAIN}/privkey.pem"
  mkdir -p "$(dirname "$SSL_CERT")" /www/wwwlogs
  if [[ ! -f "$SSL_CERT" || -L "$SSL_CERT" ]]; then
    rm -f "$SSL_CERT" "$SSL_KEY"
    openssl req -x509 -nodes -newkey rsa:2048 -days 2 \
      -keyout "$SSL_KEY" -out "$SSL_CERT" \
      -subj "/CN=${DOMAIN}" >/dev/null 2>&1
  fi

  local tmp
  tmp="$(mktemp)"
  sed \
    -e "s|__SSL_CERT__|${SSL_CERT}|g" \
    -e "s|__SSL_KEY__|${SSL_KEY}|g" \
    -e "s|__CYPHT_HOST_PORT__|${HOST_PORT}|g" \
    "$NGINX_TMPL" > "$tmp"

  mkdir -p "$(dirname "$NGINX_VHOST")"
  cp -a "$tmp" "$NGINX_VHOST"
  rm -f "$tmp"

  local stopped
  for stopped in \
    "/www/server/stop/${DOMAIN}.conf" \
    "/www/server/panel/vhost/nginx/${DOMAIN}.conf.stop" \
    "/www/server/panel/vhost/nginx/stop/${DOMAIN}.conf"; do
    [[ -e "$stopped" ]] && rm -f "$stopped" && info "Removed stopped-site marker $stopped"
  done

  nginx -t 2>&1 | tee /tmp/cypht-nginx-test.log >/dev/null || {
    cat /tmp/cypht-nginx-test.log >&2
    fail "nginx -t failed after writing $NGINX_VHOST"
  }
  nginx -s reload 2>/dev/null || systemctl reload nginx 2>/dev/null || true

  if [[ "${CYPHT_SKIP_SSL:-0}" != "1" ]]; then
    install_domain_cert
    sed -i \
      -e "s|ssl_certificate    .*|ssl_certificate    ${SSL_CERT};|" \
      -e "s|ssl_certificate_key    .*|ssl_certificate_key    ${SSL_KEY};|" \
      "$NGINX_VHOST" || true
    nginx -t 2>&1 | tee /tmp/cypht-nginx-test.log >/dev/null || {
      cat /tmp/cypht-nginx-test.log >&2
      fail "nginx -t failed after SSL install"
    }
  fi

  if systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null; then
    info "nginx reloaded with $NGINX_VHOST"
  else
    warn "Could not reload nginx — run: nginx -t && nginx -s reload"
  fi
}

write_systemd() {
  mkdir -p "$LOG_DIR"
  touch "$CYPHT_LOG"
  chmod 644 "$CYPHT_LOG"

  cat > "$UNIT_PATH" <<EOF
[Unit]
Description=VoxBulk Cypht multi-account webmail (Docker Compose)
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${DATA_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=/usr/bin/docker compose -f ${COMPOSE_LINK} --env-file ${ENV_FILE} up -d --remove-orphans
ExecStop=/usr/bin/docker compose -f ${COMPOSE_LINK} --env-file ${ENV_FILE} stop
ExecReload=/usr/bin/docker compose -f ${COMPOSE_LINK} --env-file ${ENV_FILE} up -d --remove-orphans
TimeoutStartSec=300
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable voxbulk-cypht.service
  info "Installed systemd unit voxbulk-cypht.service (WantedBy=multi-user.target)"
}

start_stack() {
  if [[ "${CYPHT_SYSTEMD_SKIP_START:-0}" == "1" ]]; then
    warn "CYPHT_SYSTEMD_SKIP_START=1 — unit enabled but not started"
    return 0
  fi
  systemctl restart voxbulk-cypht.service
  sleep 3
  if systemctl is-active --quiet voxbulk-cypht.service; then
    info "voxbulk-cypht.service is active"
  else
    systemctl status voxbulk-cypht.service --no-pager -l || true
    fail "Cypht service failed to start — check: journalctl -u voxbulk-cypht -n 80"
  fi
  # Wait for HTTP on localhost
  local i
  for i in $(seq 1 30); do
    if curl -fsS -o /dev/null -m 3 "http://127.0.0.1:${HOST_PORT}/" 2>/dev/null; then
      info "Cypht responding on 127.0.0.1:${HOST_PORT}"
      break
    fi
    sleep 2
  done
}

print_status() {
  echo ""
  info "Done."
  echo "  URL:     https://${DOMAIN}"
  echo "  Creds:   $ENV_FILE  (CYPHT_ADMIN_USER / CYPHT_ADMIN_PASSWORD)"
  echo "  Stack:   systemctl status voxbulk-cypht"
  echo "  Logs:    docker compose -f $COMPOSE_LINK --env-file $ENV_FILE logs -f --tail=100"
  echo ""
  echo "Next: open https://${DOMAIN}, sign in, then Settings → Servers → add each IMAP/SMTP account."
}

# ── main ─────────────────────────────────────────────────────────────────────
info "Installing Cypht for https://${DOMAIN}"
ensure_docker
ensure_env
link_compose
write_systemd
start_stack
write_nginx
print_status
