/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SmartCardRouteImport } from './routes/smart-card'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LegalPoliciesRouteImport } from './routes/legal-policies'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExpoRouteImport } from './routes/expo'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as KeyDottxtRouteImport } from './routes/$key[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SmartCardIndexRouteImport } from './routes/smart-card.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as ExpoIndexRouteImport } from './routes/expo.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SurveyTokenRouteImport } from './routes/survey.$token'
import { Route as SmartcardTokenRouteImport } from './routes/smartcard.$token'
import { Route as SmartCardTokenRouteImport } from './routes/smart-card.$token'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as HelpZohoRecruitRouteImport } from './routes/help.zoho-recruit'
import { Route as HelpArticlesRouteImport } from './routes/help.articles'
import { Route as FaqSlugRouteImport } from './routes/faq.$slug'
import { Route as ExpoTokenRouteImport } from './routes/expo.$token'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as HelpArticlesIndexRouteImport } from './routes/help.articles.index'
import { Route as SurveyPreviewThemeIdRouteImport } from './routes/survey.preview.$themeId'
import { Route as HelpArticlesSlugRouteImport } from './routes/help.articles.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartCardRoute = SmartCardRouteImport.update({
  id: '/smart-card',
  path: '/smart-card',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPoliciesRoute = LegalPoliciesRouteImport.update({
  id: '/legal-policies',
  path: '/legal-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpoRoute = ExpoRouteImport.update({
  id: '/expo',
  path: '/expo',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyDottxtRoute = KeyDottxtRouteImport.update({
  id: '/$key.txt',
  path: '/$key.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartCardIndexRoute = SmartCardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SmartCardRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FaqRoute,
} as any)
const ExpoIndexRoute = ExpoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpoRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const SurveyTokenRoute = SurveyTokenRouteImport.update({
  id: '/survey/$token',
  path: '/survey/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartcardTokenRoute = SmartcardTokenRouteImport.update({
  id: '/smartcard/$token',
  path: '/smartcard/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartCardTokenRoute = SmartCardTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => SmartCardRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const HelpZohoRecruitRoute = HelpZohoRecruitRouteImport.update({
  id: '/zoho-recruit',
  path: '/zoho-recruit',
  getParentRoute: () => HelpRoute,
} as any)
const HelpArticlesRoute = HelpArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => HelpRoute,
} as any)
const FaqSlugRoute = FaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FaqRoute,
} as any)
const ExpoTokenRoute = ExpoTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ExpoRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const HelpArticlesIndexRoute = HelpArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpArticlesRoute,
} as any)
const SurveyPreviewThemeIdRoute = SurveyPreviewThemeIdRouteImport.update({
  id: '/survey/preview/$themeId',
  path: '/survey/preview/$themeId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpArticlesSlugRoute = HelpArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HelpArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$key.txt': typeof KeyDottxtRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/expo': typeof ExpoRouteWithChildren
  '/faq': typeof FaqRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/gdpr': typeof GdprRoute
  '/help': typeof HelpRouteWithChildren
  '/legal': typeof LegalRoute
  '/legal-policies': typeof LegalPoliciesRoute
  '/news': typeof NewsRouteWithChildren
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recruitment': typeof RecruitmentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-card': typeof SmartCardRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/expo/$token': typeof ExpoTokenRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/help/articles': typeof HelpArticlesRouteWithChildren
  '/help/zoho-recruit': typeof HelpZohoRecruitRoute
  '/news/$slug': typeof NewsSlugRoute
  '/smart-card/$token': typeof SmartCardTokenRoute
  '/smartcard/$token': typeof SmartcardTokenRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/expo/': typeof ExpoIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/help/': typeof HelpIndexRoute
  '/news/': typeof NewsIndexRoute
  '/smart-card/': typeof SmartCardIndexRoute
  '/help/articles/$slug': typeof HelpArticlesSlugRoute
  '/survey/preview/$themeId': typeof SurveyPreviewThemeIdRoute
  '/help/articles/': typeof HelpArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$key.txt': typeof KeyDottxtRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/feedback': typeof FeedbackRoute
  '/gdpr': typeof GdprRoute
  '/legal': typeof LegalRoute
  '/legal-policies': typeof LegalPoliciesRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recruitment': typeof RecruitmentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surveys': typeof SurveysRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/expo/$token': typeof ExpoTokenRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/help/zoho-recruit': typeof HelpZohoRecruitRoute
  '/news/$slug': typeof NewsSlugRoute
  '/smart-card/$token': typeof SmartCardTokenRoute
  '/smartcard/$token': typeof SmartcardTokenRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/blog': typeof BlogIndexRoute
  '/expo': typeof ExpoIndexRoute
  '/faq': typeof FaqIndexRoute
  '/help': typeof HelpIndexRoute
  '/news': typeof NewsIndexRoute
  '/smart-card': typeof SmartCardIndexRoute
  '/help/articles/$slug': typeof HelpArticlesSlugRoute
  '/survey/preview/$themeId': typeof SurveyPreviewThemeIdRoute
  '/help/articles': typeof HelpArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$key.txt': typeof KeyDottxtRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/expo': typeof ExpoRouteWithChildren
  '/faq': typeof FaqRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/gdpr': typeof GdprRoute
  '/help': typeof HelpRouteWithChildren
  '/legal': typeof LegalRoute
  '/legal-policies': typeof LegalPoliciesRoute
  '/news': typeof NewsRouteWithChildren
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recruitment': typeof RecruitmentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-card': typeof SmartCardRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/expo/$token': typeof ExpoTokenRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/help/articles': typeof HelpArticlesRouteWithChildren
  '/help/zoho-recruit': typeof HelpZohoRecruitRoute
  '/news/$slug': typeof NewsSlugRoute
  '/smart-card/$token': typeof SmartCardTokenRoute
  '/smartcard/$token': typeof SmartcardTokenRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/expo/': typeof ExpoIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/help/': typeof HelpIndexRoute
  '/news/': typeof NewsIndexRoute
  '/smart-card/': typeof SmartCardIndexRoute
  '/help/articles/$slug': typeof HelpArticlesSlugRoute
  '/survey/preview/$themeId': typeof SurveyPreviewThemeIdRoute
  '/help/articles/': typeof HelpArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$key.txt'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/dpa'
    | '/expo'
    | '/faq'
    | '/feedback'
    | '/gdpr'
    | '/help'
    | '/legal'
    | '/legal-policies'
    | '/news'
    | '/news-sitemap.xml'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/recruitment'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/sitemap.xml'
    | '/smart-card'
    | '/surveys'
    | '/terms'
    | '/blog/$slug'
    | '/expo/$token'
    | '/faq/$slug'
    | '/help/articles'
    | '/help/zoho-recruit'
    | '/news/$slug'
    | '/smart-card/$token'
    | '/smartcard/$token'
    | '/survey/$token'
    | '/blog/'
    | '/expo/'
    | '/faq/'
    | '/help/'
    | '/news/'
    | '/smart-card/'
    | '/help/articles/$slug'
    | '/survey/preview/$themeId'
    | '/help/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$key.txt'
    | '/contact'
    | '/cookies'
    | '/dpa'
    | '/feedback'
    | '/gdpr'
    | '/legal'
    | '/legal-policies'
    | '/news-sitemap.xml'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/recruitment'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/sitemap.xml'
    | '/surveys'
    | '/terms'
    | '/blog/$slug'
    | '/expo/$token'
    | '/faq/$slug'
    | '/help/zoho-recruit'
    | '/news/$slug'
    | '/smart-card/$token'
    | '/smartcard/$token'
    | '/survey/$token'
    | '/blog'
    | '/expo'
    | '/faq'
    | '/help'
    | '/news'
    | '/smart-card'
    | '/help/articles/$slug'
    | '/survey/preview/$themeId'
    | '/help/articles'
  id:
    | '__root__'
    | '/'
    | '/$key.txt'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/dpa'
    | '/expo'
    | '/faq'
    | '/feedback'
    | '/gdpr'
    | '/help'
    | '/legal'
    | '/legal-policies'
    | '/news'
    | '/news-sitemap.xml'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/recruitment'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/sitemap.xml'
    | '/smart-card'
    | '/surveys'
    | '/terms'
    | '/blog/$slug'
    | '/expo/$token'
    | '/faq/$slug'
    | '/help/articles'
    | '/help/zoho-recruit'
    | '/news/$slug'
    | '/smart-card/$token'
    | '/smartcard/$token'
    | '/survey/$token'
    | '/blog/'
    | '/expo/'
    | '/faq/'
    | '/help/'
    | '/news/'
    | '/smart-card/'
    | '/help/articles/$slug'
    | '/survey/preview/$themeId'
    | '/help/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeyDottxtRoute: typeof KeyDottxtRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DpaRoute: typeof DpaRoute
  ExpoRoute: typeof ExpoRouteWithChildren
  FaqRoute: typeof FaqRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  GdprRoute: typeof GdprRoute
  HelpRoute: typeof HelpRouteWithChildren
  LegalRoute: typeof LegalRoute
  LegalPoliciesRoute: typeof LegalPoliciesRoute
  NewsRoute: typeof NewsRouteWithChildren
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecruitmentRoute: typeof RecruitmentRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmartCardRoute: typeof SmartCardRouteWithChildren
  SurveysRoute: typeof SurveysRoute
  TermsRoute: typeof TermsRoute
  SmartcardTokenRoute: typeof SmartcardTokenRoute
  SurveyTokenRoute: typeof SurveyTokenRoute
  SurveyPreviewThemeIdRoute: typeof SurveyPreviewThemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-card': {
      id: '/smart-card'
      path: '/smart-card'
      fullPath: '/smart-card'
      preLoaderRoute: typeof SmartCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-policies': {
      id: '/legal-policies'
      path: '/legal-policies'
      fullPath: '/legal-policies'
      preLoaderRoute: typeof LegalPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expo': {
      id: '/expo'
      path: '/expo'
      fullPath: '/expo'
      preLoaderRoute: typeof ExpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$key.txt': {
      id: '/$key.txt'
      path: '/$key.txt'
      fullPath: '/$key.txt'
      preLoaderRoute: typeof KeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-card/': {
      id: '/smart-card/'
      path: '/'
      fullPath: '/smart-card/'
      preLoaderRoute: typeof SmartCardIndexRouteImport
      parentRoute: typeof SmartCardRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/faq/': {
      id: '/faq/'
      path: '/'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof FaqRoute
    }
    '/expo/': {
      id: '/expo/'
      path: '/'
      fullPath: '/expo/'
      preLoaderRoute: typeof ExpoIndexRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/survey/$token': {
      id: '/survey/$token'
      path: '/survey/$token'
      fullPath: '/survey/$token'
      preLoaderRoute: typeof SurveyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smartcard/$token': {
      id: '/smartcard/$token'
      path: '/smartcard/$token'
      fullPath: '/smartcard/$token'
      preLoaderRoute: typeof SmartcardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-card/$token': {
      id: '/smart-card/$token'
      path: '/$token'
      fullPath: '/smart-card/$token'
      preLoaderRoute: typeof SmartCardTokenRouteImport
      parentRoute: typeof SmartCardRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/help/zoho-recruit': {
      id: '/help/zoho-recruit'
      path: '/zoho-recruit'
      fullPath: '/help/zoho-recruit'
      preLoaderRoute: typeof HelpZohoRecruitRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/articles': {
      id: '/help/articles'
      path: '/articles'
      fullPath: '/help/articles'
      preLoaderRoute: typeof HelpArticlesRouteImport
      parentRoute: typeof HelpRoute
    }
    '/faq/$slug': {
      id: '/faq/$slug'
      path: '/$slug'
      fullPath: '/faq/$slug'
      preLoaderRoute: typeof FaqSlugRouteImport
      parentRoute: typeof FaqRoute
    }
    '/expo/$token': {
      id: '/expo/$token'
      path: '/$token'
      fullPath: '/expo/$token'
      preLoaderRoute: typeof ExpoTokenRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/help/articles/': {
      id: '/help/articles/'
      path: '/'
      fullPath: '/help/articles/'
      preLoaderRoute: typeof HelpArticlesIndexRouteImport
      parentRoute: typeof HelpArticlesRoute
    }
    '/survey/preview/$themeId': {
      id: '/survey/preview/$themeId'
      path: '/survey/preview/$themeId'
      fullPath: '/survey/preview/$themeId'
      preLoaderRoute: typeof SurveyPreviewThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/articles/$slug': {
      id: '/help/articles/$slug'
      path: '/$slug'
      fullPath: '/help/articles/$slug'
      preLoaderRoute: typeof HelpArticlesSlugRouteImport
      parentRoute: typeof HelpArticlesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ExpoRouteChildren {
  ExpoTokenRoute: typeof ExpoTokenRoute
  ExpoIndexRoute: typeof ExpoIndexRoute
}

const ExpoRouteChildren: ExpoRouteChildren = {
  ExpoTokenRoute: ExpoTokenRoute,
  ExpoIndexRoute: ExpoIndexRoute,
}

const ExpoRouteWithChildren = ExpoRoute._addFileChildren(ExpoRouteChildren)

interface FaqRouteChildren {
  FaqSlugRoute: typeof FaqSlugRoute
  FaqIndexRoute: typeof FaqIndexRoute
}

const FaqRouteChildren: FaqRouteChildren = {
  FaqSlugRoute: FaqSlugRoute,
  FaqIndexRoute: FaqIndexRoute,
}

const FaqRouteWithChildren = FaqRoute._addFileChildren(FaqRouteChildren)

interface HelpArticlesRouteChildren {
  HelpArticlesSlugRoute: typeof HelpArticlesSlugRoute
  HelpArticlesIndexRoute: typeof HelpArticlesIndexRoute
}

const HelpArticlesRouteChildren: HelpArticlesRouteChildren = {
  HelpArticlesSlugRoute: HelpArticlesSlugRoute,
  HelpArticlesIndexRoute: HelpArticlesIndexRoute,
}

const HelpArticlesRouteWithChildren = HelpArticlesRoute._addFileChildren(
  HelpArticlesRouteChildren,
)

interface HelpRouteChildren {
  HelpArticlesRoute: typeof HelpArticlesRouteWithChildren
  HelpZohoRecruitRoute: typeof HelpZohoRecruitRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpArticlesRoute: HelpArticlesRouteWithChildren,
  HelpZohoRecruitRoute: HelpZohoRecruitRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface SmartCardRouteChildren {
  SmartCardTokenRoute: typeof SmartCardTokenRoute
  SmartCardIndexRoute: typeof SmartCardIndexRoute
}

const SmartCardRouteChildren: SmartCardRouteChildren = {
  SmartCardTokenRoute: SmartCardTokenRoute,
  SmartCardIndexRoute: SmartCardIndexRoute,
}

const SmartCardRouteWithChildren = SmartCardRoute._addFileChildren(
  SmartCardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeyDottxtRoute: KeyDottxtRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DpaRoute: DpaRoute,
  ExpoRoute: ExpoRouteWithChildren,
  FaqRoute: FaqRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  GdprRoute: GdprRoute,
  HelpRoute: HelpRouteWithChildren,
  LegalRoute: LegalRoute,
  LegalPoliciesRoute: LegalPoliciesRoute,
  NewsRoute: NewsRouteWithChildren,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecruitmentRoute: RecruitmentRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmartCardRoute: SmartCardRouteWithChildren,
  SurveysRoute: SurveysRoute,
  TermsRoute: TermsRoute,
  SmartcardTokenRoute: SmartcardTokenRoute,
  SurveyTokenRoute: SurveyTokenRoute,
  SurveyPreviewThemeIdRoute: SurveyPreviewThemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
