import React, { useEffect, useState } from 'react'
import { AlertTriangle, ShieldCheck } from 'lucide-react'
import { apiFetch } from '../lib/api'
import { Button } from '@/components/ui/Button'
import SupportDiskShell from '../components/supportDisk/SupportDiskShell'
import { StatusPill } from '../components/supportDisk/bits'

export default function SupportSLA() {
  const [settings, setSettings] = useState([]), [breaches, setBreaches] = useState([]), [error, setError] = useState('')
  const load = async () => { try { const [s, b] = await Promise.all([apiFetch('/admin/support/sla-settings'), apiFetch('/admin/support/sla-breaches')]); setSettings(Array.isArray(s) ? s : s?.policies || []); setBreaches(Array.isArray(b) ? b : b?.breaches || []) } catch (e) { setError(e.message) } }
  useEffect(() => { load() }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const save = async () => { await apiFetch('/admin/support/sla-settings', { method: 'PUT', body: { policies: settings } }); load() }
  const compliance = settings.length ? Math.round(settings.reduce((n, p) => n + Number(p.compliance || 0), 0) / settings.length) : 0
  return <SupportDiskShell title="SLA & KPIs" subtitle="Compliance, breach warnings and policy targets" actions={<Button size="sm" onClick={save}>Save policies</Button>}><div className="h-full overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-4">{error ? <div className="rounded-lg border border-destructive/30 p-3 text-sm text-destructive">{error}</div> : null}<div className="grid gap-3 sm:grid-cols-3">{[['Overall SLA compliance', `${compliance}%`, 'Target 95%'], ['Breaches', breaches.filter((x) => x.breached !== false).length, 'Needs action'], ['At-risk right now', breaches.filter((x) => x.breached === false).length, 'Due soon']].map(([label, value, note]) => <div key={label} className="rounded-xl border border-border bg-surface p-4 shadow-panel"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-display text-2xl font-extrabold">{value}</p><p className="text-xs text-muted-foreground">{note}</p></div>)}</div>
    <section className="rounded-xl border border-priority-urgent/25 bg-surface shadow-panel"><header className="flex items-center gap-2 border-b p-3"><AlertTriangle className="size-4 text-priority-urgent" /><h2 className="text-sm font-bold">Breach warnings</h2></header><ul className="divide-y">{breaches.map((t) => <li key={t.id || t.ticket_id} className="flex items-center gap-3 p-3"><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{t.public_ref} · {t.subject}</strong><span className="text-xs text-muted-foreground">{t.organisation_name} · {t.assigned_admin_email || 'Unassigned'}</span></div><StatusPill status={t.status || 'open'} /><span className={t.breached === false ? 'text-status-pending' : 'text-priority-urgent'}>{t.label || (t.breached === false ? 'At risk' : 'Breached')}</span></li>)}</ul></section>
    <section className="rounded-xl border border-border bg-surface shadow-panel"><header className="flex items-center gap-2 border-b p-3"><ShieldCheck className="size-4 text-status-resolved" /><h2 className="text-sm font-bold">Policy compliance</h2></header><ul className="divide-y">{settings.map((p, i) => <li key={p.id || p.name || i} className="grid gap-3 p-3 sm:grid-cols-[1fr_130px_130px]"><input value={p.name || ''} onChange={(e) => setSettings((s) => s.map((x, j) => j === i ? { ...x, name: e.target.value } : x))} className="h-9 rounded-md border px-3" /><input type="number" value={p.first_reply_minutes || 0} onChange={(e) => setSettings((s) => s.map((x, j) => j === i ? { ...x, first_reply_minutes: Number(e.target.value) } : x))} className="h-9 rounded-md border px-3" title="First reply minutes" /><input type="number" value={p.resolution_minutes || 0} onChange={(e) => setSettings((s) => s.map((x, j) => j === i ? { ...x, resolution_minutes: Number(e.target.value) } : x))} className="h-9 rounded-md border px-3" title="Resolution minutes" /></li>)}</ul></section>
  </div></div></SupportDiskShell>
}
