import React, { useEffect, useState } from 'react'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import { apiFetch } from '../lib/api'
import { Button } from '@/components/ui/Button'
import { Modal } from '@/components/ui/Modal'
import SupportDiskShell from '../components/supportDisk/SupportDiskShell'

const empty = { title: '', question: '', answer: '', category_id: '', is_active: true }
export default function SupportCannedReplies() {
  const [rows, setRows] = useState([]), [categories, setCategories] = useState([]), [form, setForm] = useState(null), [error, setError] = useState('')
  const load = async () => { try { const [r, c] = await Promise.all([apiFetch('/admin/support/canned/replies'), apiFetch('/admin/support/canned/categories')]); setRows(r || []); setCategories(c || []) } catch (e) { setError(e.message) } }
  useEffect(() => { load() }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const save = async () => { await apiFetch(form.id ? `/admin/support/canned/replies/${form.id}` : '/admin/support/canned/replies', { method: form.id ? 'PUT' : 'POST', body: { ...form, category_id: form.category_id ? Number(form.category_id) : null } }); setForm(null); load() }
  return <SupportDiskShell title="Canned replies" subtitle="Reusable Support Disk responses" actions={<Button size="sm" onClick={() => setForm(empty)}><Plus /> New reply</Button>}><div className="p-4 sm:p-6"><div className="mx-auto max-w-6xl overflow-hidden rounded-xl border border-border bg-surface shadow-panel">{error ? <p className="p-3 text-destructive">{error}</p> : null}<table className="w-full text-sm"><thead className="bg-surface-subtle text-left text-xs text-muted-foreground"><tr><th className="p-3">Title</th><th>Category</th><th>Status</th><th /></tr></thead><tbody className="divide-y divide-border">{rows.map((r) => <tr key={r.id}><td className="p-3"><strong>{r.title}</strong><p className="line-clamp-1 text-xs text-muted-foreground">{r.answer}</p></td><td>{r.category_name || 'Uncategorised'}</td><td>{r.is_active ? 'Active' : 'Inactive'}</td><td className="text-right"><Button variant="ghost" size="icon" onClick={() => setForm(r)}><Pencil /></Button><Button variant="ghost" size="icon" className="text-destructive" onClick={async () => { if (window.confirm('Delete this reply?')) { await apiFetch(`/admin/support/canned/replies/${r.id}`, { method: 'DELETE' }); load() } }}><Trash2 /></Button></td></tr>)}</tbody></table></div></div>
    <Modal open={!!form} onOpenChange={(o) => !o && setForm(null)} className="support-disk support-disk-dialog max-w-lg" title={form?.id ? 'Edit canned reply' : 'New canned reply'} footer={<><Button variant="ghost" onClick={() => setForm(null)}>Cancel</Button><Button onClick={save}>Save</Button></>}><div className="space-y-3"><select value={form?.category_id || ''} onChange={(e) => setForm({ ...form, category_id: e.target.value })} className="h-9 w-full rounded-md border px-3"><option value="">No category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input value={form?.title || ''} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Short title" className="h-9 w-full rounded-md border px-3" /><textarea value={form?.question || ''} onChange={(e) => setForm({ ...form, question: e.target.value })} placeholder="When to use" className="min-h-20 w-full rounded-md border p-3" /><textarea value={form?.answer || ''} onChange={(e) => setForm({ ...form, answer: e.target.value })} placeholder="Reply text" className="min-h-36 w-full rounded-md border p-3" /></div></Modal>
  </SupportDiskShell>
}
